### **INSTALLATION OF ALL PACKAGES**

In [ ]:
!pip install pymupdf pandas
!pip install -q pdfplumber pandas tqdm


import re, pdfplumber, pandas as pd
from pathlib import Path
from tqdm.auto import tqdm




   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 65.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 94.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 103.8 MB/s eta 0:00:00


In [ ]:
!python -m spacy download en_core_web_sm
!pip install geotext

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 109.8 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 32.7 MB/s eta 0:00:00


In [ ]:
import json
import spacy
import re
import re
from typing import Dict
import spacy
nlp = spacy.load("en_core_web_sm")
ruler = nlp.add_pipe("entity_ruler", before="ner")


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### **MODULE PREPARATION OF DETERMINISTIC RULES FOR YES/NO/MULTIPLECHOICE/NON-SCORING QUESTION-TYPES**

In [ ]:
%%writefile yesnorules.py
"""
Rule‑based classifier for the simple Yes/No & information‑only questions
used in the Cyber‑Essentials free‑text dataset.

Returns a tuple (label, short_reason).
"""

import re

# ──────────────────────────────────────────────────────────────────
# 1.  ID buckets
# ──────────────────────────────────────────────────────────────────
INFO_ONLY_IDS = {
    "A1.1","A1.2","A1.3","A1.4","A1.5","A1.6","A1.7",
    "A1.8","A1.8.1","A1.8.2","A1.8.3","A1.8.4","A1.8.5",
    "A1.10",
    "A3.1","A3.2","A3.3","A3.4",
    "A4.11",
    "A5.7",
    "A6.4.1","A6.5.1","A1.11","A7.15"
}

YES_NO_ACCEPT_NO_IDS = {"A4.5", "A7.14"}

YES_NO_MUST_CHECK_NOTES_IDS = {
    "A4.1","A4.2","A4.4","A4.7","A4.9",
    "A5.2","A5.3","A5.8","A5.9",
    "A6.1","A6.2","A6.3","A6.4","A6.5","A6.6",
    "A7.2","A7.8","A7.9","A7.13","A7.16","A7.17",
    "A1.9",
    "A8.2","A8.3","A8.4","A8.5","A4.5.1"
}

YES_NO_NON_SCORING_IDS = {"A2.1","A3.1","A4.8","A4.11","A5.4"}

# IDs that have bespoke logic later in the file
SPECIAL_CASE_IDS = {"A4.3", "A5.5", "A8.1"}

RULE_IDS = (
      INFO_ONLY_IDS
    | YES_NO_ACCEPT_NO_IDS
    | YES_NO_MUST_CHECK_NOTES_IDS
    | YES_NO_NON_SCORING_IDS
    | SPECIAL_CASE_IDS           # ← ensures they’re in the mask
)

# ──────────────────────────────────────────────────────────────────
# 2.  Helpers
# ──────────────────────────────────────────────────────────────────
def _is_blank(txt: str) -> bool:
    """Common ‘blank’ placeholders."""
    return txt.strip().lower() in {"", "n/a", "na", "none", "not applicable"}

# ──────────────────────────────────────────────────────────────────
# 3.  Main classifier
# ──────────────────────────────────────────────────────────────────
def classify_compliance_with_reason(row):
    """
    Parameters
    ----------
    row : pandas.Series with at least
        - question_id
        - answer_text
        - auto_fail_blank  (optional boolean/str)

    Returns
    -------
    (label, reason)   e.g. ("Compliant", "Answered 'Yes' (compliant)")
    """
    qid = row.get("question_id", "")
    ans = str(row.get("answer_text", "")).strip().lower()
    auto_fail = str(row.get("auto_fail_blank", "False")).lower() == "true"
    blank = _is_blank(ans)

    # — 3.1 generic guards —
    if "[redacted]" in ans:
        return "Compliant", "Answer is redacted (accepted as compliant)"
    if auto_fail:
        return "Fail", "Marked as auto‑fail due to blank or flag"

    # — 3.2 bucket rules —
    if qid in INFO_ONLY_IDS:
        return (
            ("Compliant", "Info‑only question with non‑blank answer")
            if not blank else
            ("Fail", "Info‑only question left blank")
        )

    if qid in YES_NO_ACCEPT_NO_IDS:
        return (
            ("Compliant", "Yes/No (No accepted) answered")
            if not blank else
            ("Fail", "Yes/No (No accepted) left blank")
        )

    if qid in YES_NO_MUST_CHECK_NOTES_IDS:
        if ans.startswith("yes"):
            return "Compliant", "Answered 'Yes' (compliant)"
        if ans.startswith("no"):
            return "Non-compliant", "Answered 'No' (non‑compliant)"
        return "Fail", "Did not answer with 'Yes' or 'No'"

    if qid in YES_NO_NON_SCORING_IDS:
        return (
            ("Compliant", "Non‑scoring Yes/No with answer")
            if not blank else
            ("Fail", "Non‑scoring Yes/No left blank")
        )

    # — 3.3 bespoke multiple‑choice rules —
    if qid in {"A4.3", "A5.5"}:
        only_d_selected = (
            re.search(r"\bd[\.\)]?\s*none of the above", ans)
            and not re.search(r"\b[abc][\.\)]", ans)
        )
        if only_d_selected:
            explanation = re.sub(r"d[\.\)]?\s*none of the above", "", ans).strip()
            if len(explanation.split()) < 8:
                return "Non-compliant", (
                    "Only 'None of the above' selected; explanation too short"
                )
        return "Compliant", "Other option selected or a valid explanation provided"

    if qid == "A8.1":
        only_c_selected = (
            re.search(r"\bc[\.\)]?\s*none of the above", ans)
            and not re.search(r"\b[abd][\.\)]", ans)
        )
        if only_c_selected:
            explanation = re.sub(r"c[\.\)]?\s*none of the above", "", ans).strip()
            if len(explanation.split()) < 8:
                return "Non-compliant", (
                    "Only 'None of the above' selected; explanation too short"
                )
        return "Compliant", "Other option selected or a valid explanation provided"

    # — 3.4 fallback —
    return "Unknown", "No matching rule applied"


Writing yesnorules.py


### **MODULE PREPARATION OF OCROSS-DEPENDENCYQUESTIONS/BLANK_OVERULE**

In [ ]:
%%writefile overulerules.py
def overrule_block(sub):
    # Only use the working column name (compliance)
    # A6.2.x → A6.2 / A6.6
    if (sub.loc[sub["question_id"].isin(["A6.2.1", "A6.2.2", "A6.2.3", "A6.2.4"]), "compliance"] == "Non-Compliant").any():
        for qid in ["A6.2", "A6.6"]:
            idx = sub["question_id"] == qid
            sub.loc[idx, "compliance"] = "Non-Compliant"

    # A4.5.1 or A4.6 → A4.5
    if (sub.loc[sub["question_id"].isin(["A4.5.1", "A4.6"]), "compliance"] == "Non-Compliant").any():
        idx = sub["question_id"] == "A4.5"
        sub.loc[idx, "compliance"] = "Non-Compliant"

    # A7.14 == “No” → A7.16 / A7.17
    try:
        a714_ans = (
            sub.loc[sub["question_id"] == "A7.14", "answer_text"].iloc[0].strip().lower()
        )
        if a714_ans in {"no", "n"}:
            for qid in ["A7.16", "A7.17"]:
                idx = sub["question_id"] == qid
                sub.loc[idx, "compliance"] = "Non-Compliant"
    except IndexError:
        pass

    # Blank / “not applicable” answers → Fail
    for i, row in sub.iterrows():
        ans = str(row["answer_text"]).strip().lower()
        if ans in {"", "n/a", "na", "none", "not applicable", "."}:
            sub.at[i, "compliance"] = "Fail"

    return sub


Writing overulerules.py


In [ ]:
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from yesnorules import RULE_IDS, classify_compliance_with_reason

# === Config: questions that MUST fail if the answer is blank ===
MUST_FAIL_IF_BLANK = {"A4.3"}

# === 1) Load ===
csv_path = "/content/drive/MyDrive/project/CB/manual_annotated_questions.csv"
df = pd.read_csv(csv_path, dtype=str).fillna("")
df["question_id"] = df["question_id"].astype(str).str.strip()

# === 2) Keep rule-based rows ===
df_rule = df[df["question_id"].isin(RULE_IDS)].copy()

# === 3) Predict label + reason (capture BOTH) ===
def is_blank(x: str) -> bool:
    return not isinstance(x, str) or x.strip() == ""

def predict_with_reason(row):
    qid = row["question_id"]
    ans = str(row["answer_text"])

    # Hard rule: must-not-be-blank
    if qid in MUST_FAIL_IF_BLANK and is_blank(ans):
        return pd.Series(["Fail", f"Auto-fail: blank answer for {qid} (CE rule)"])

    label, reason = classify_compliance_with_reason({
        "question_id": qid,
        "answer_text": ans.strip(),
    })
    # Ensure reason is a non-empty string
    if reason is None or str(reason).strip() == "":
        reason = f"Rule-based decision for {qid}"
    return pd.Series([label, reason])

df_rule[["predicted_compliance", "reason"]] = df_rule.apply(predict_with_reason, axis=1)

# === 4) Normalise labels ===
def normalize_label(label):
    if not isinstance(label, str): return ""
    s = label.strip().lower()
    if s in {"non-compliant", "non compliant", "noncompliant"}: return "Non-compliant"
    if s == "compliant": return "Compliant"
    if s in {"fail", "failed"}: return "Fail"
    if s in {"more-information", "more information", "more info", "moreinformation", "more_info"}: return "More-information"
    if s in {"unknown", "n/a", "na"}: return "Unknown"
    return s.capitalize()

df_rule["compliance"] = df_rule["compliance"].apply(normalize_label)
df_rule["predicted_compliance"] = df_rule["predicted_compliance"].apply(normalize_label)

# === 5) Filter valid rows for evaluation ===
df_eval = df_rule[
    (df_rule["compliance"] != "") &
    (df_rule["predicted_compliance"] != "") &
    (df_rule["predicted_compliance"] != "Unknown")
].copy()

# === 6) Metrics ===
print("=== Classification Report ===")
print(classification_report(
    df_eval["compliance"],
    df_eval["predicted_compliance"],
    labels=["Compliant", "Non-compliant", "Fail", "More-information"],
    zero_division=0
))

print("\n=== Confusion Matrix ===")
print(confusion_matrix(
    df_eval["compliance"],
    df_eval["predicted_compliance"],
    labels=["Compliant", "Non-compliant", "Fail", "More-information"]
))

# === 8) Mismatches with reasons (no KeyError now) ===
mismatches = df_eval[df_eval["compliance"] != df_eval["predicted_compliance"]]
print(f"\n❌ Mismatches: {len(mismatches)}")

# === 9) Unique Question IDs with mismatches ===
if not mismatches.empty:
    unique_mismatch_ids = mismatches["question_id"].unique()
    print("Unique question IDs with mismatches:")
    for qid in unique_mismatch_ids:
        count = (mismatches["question_id"] == qid).sum()
        print(f" - {qid}  ({count} cases)")
else:
    print("✅ No mismatches found.")

cols = ["file", "question_id", "answer_text", "compliance", "predicted_compliance", "reason"]
available_cols = [c for c in cols if c in mismatches.columns]
try:
    display(mismatches[available_cols].head(10))
except NameError:
    print(mismatches[available_cols].head(10).to_string(index=False))


=== Classification Report ===
                  precision    recall  f1-score   support

       Compliant       1.00      1.00      1.00      2908
   Non-compliant       1.00      0.57      0.73        21
            Fail       1.00      1.00      1.00       130
More-information       0.00      0.00      0.00         0

        accuracy                           1.00      3059
       macro avg       0.75      0.64      0.68      3059
    weighted avg       1.00      1.00      1.00      3059


=== Confusion Matrix ===
[[2908    0    0    0]
 [   9   12    0    0]
 [   0    0  130    0]
 [   0    0    0    0]]

❌ Mismatches: 9
Unique question IDs with mismatches:
 - A6.2  (3 cases)
 - A6.6  (3 cases)
 - A4.5  (3 cases)


file question_id  \
1442  answers (26).pdf        A6.2   
1454  answers (26).pdf        A6.6   
1583  answers (28).pdf        A4.5   
2449  answers (38).pdf        A6.2   
2461  answers (38).pdf        A6.6   
2523  answers (39).pdf        A6.2   
2535  answers (39).pdf        A6.6   
2590   answers (4).pdf        A4.5   
3208  answers (47).pdf        A4.5   

                                            answer_text     compliance  \
1442                                                Yes  Non-compliant   
1454                                                Yes  Non-compliant   
1583  Yes\nNotes:\nApplicant Notes: P3 has a website...  Non-compliant   
2449                                                Yes  Non-compliant   
2461                                                Yes  Non-compliant   
2523                                                Yes  Non-compliant   
2535                                 Yes\nAnswer Export  Non-compliant   
2590  Yes\nNotes:\nApplicant Notes: Synology Drive a...  Non-compliant   
3208  Yes\nNotes:\nApplicant Notes: Homeworkers usin...  Non-compliant   

     predicted_compliance                         reason  
1442            Compliant     Answered 'Yes' (compliant)  
1454            Compliant     Answered 'Yes' (compliant)  
1583            Compliant  Yes/No (No accepted) answered  
2449            Compliant     Answered 'Yes' (compliant)  
2461            Compliant     Answered 'Yes' (compliant)  
2523            Compliant     Answered 'Yes' (compliant)  
2535            Compliant     Answered 'Yes' (compliant)  
2590            Compliant  Yes/No (No accepted) answered  
3208            Compliant  Yes/No (No accepted) answered

The rules engine was evaluated on 3,059 rule-eligible items. Overall accuracy was 99.7% (rounded to 1.00). Compliant cases matched perfectly (P/R/F1 = 1.00), and Fail also achieved full agreement (130/130; P/R/F1 = 1.00). Non-Compliant showed precision 1.00 and recall 0.57; nine of 21 Non-Compliant cases were predicted Compliant. No More-Information items occurred. All mismatches arose from parent items (A6.2, A6.6, A4.5) that inherit status from dependent checks and are corrected by cross-question overrides in the fused pipeline. The rule component therefore aligns closely with the development corpus.

### Evaluation of Reasons outputs

In [ ]:
import pandas as pd
import re

from yesnorules import RULE_IDS, classify_compliance_with_reason

# === 1) Load annotated dataset ===
csv_path = "/content/drive/MyDrive/project/CB/manual_annotated_questions.csv"
df = pd.read_csv(csv_path, dtype=str).fillna("")

# === 2) Filter only closed-rule question IDs ===
df_rule = df[df["question_id"].isin(RULE_IDS)].copy()

# === 3) Predict (label, reason) ===
def get_prediction_and_reason(row):
    label, reason = classify_compliance_with_reason({
        "question_id": row["question_id"],
        "answer_text": str(row["answer_text"]).strip(),
    })
    return pd.Series([label, reason])

df_rule[["predicted_compliance", "reason"]] = df_rule.apply(get_prediction_and_reason, axis=1)

# === 4) Normalise labels for grouping ===
def norm_label(s):
    if not isinstance(s, str): return ""
    t = s.strip().lower()
    if t in {"non-compliant", "non compliant", "noncompliant"}: return "Non-compliant"
    if t == "compliant": return "Compliant"
    if t in {"fail", "failed"}: return "Fail"
    if t in {"more-information", "more information", "moreinformation", "more info"}: return "More-information"
    if t == "unknown": return "Unknown"
    return t.capitalize()

df_rule["predicted_compliance"] = df_rule["predicted_compliance"].apply(norm_label)

# ---------------------------------------------------------------------
# === 5) Evaluation tailored to YES/NO/INFO rules
# ---------------------------------------------------------------------

# 5a. Coverage: % predictions with a non-empty reason
total = len(df_rule)
has_reason = df_rule["reason"].astype(str).str.strip().ne("") & df_rule["reason"].notna()
num_with_reason = int(has_reason.sum())
pct_with_reason = 0.0 if total == 0 else 100.0 * num_with_reason / total
print(f"Reason coverage (rules-only): {num_with_reason}/{total} ({pct_with_reason:.2f}%)")

by_label = (
    df_rule.assign(has_reason=has_reason.astype(int))
           .groupby("predicted_compliance")["has_reason"]
           .agg(total="count", with_reason="sum")
)
by_label["pct_with_reason"] = 100.0 * by_label["with_reason"] / by_label["total"].clip(lower=1)
print("\nCoverage by predicted label:")
print(by_label.sort_index().to_string())

# 5b. Consistency: unique reasons per (question_id, label)
reason_var = (
    df_rule.groupby(["question_id", "predicted_compliance"])["reason"]
           .nunique()
           .reset_index(name="unique_reasons")
           .sort_values("unique_reasons", ascending=False)
)
print("\nTop variability in reasons (more unique = less consistent):")
print(reason_var.head(15).to_string(index=False))


# 5c. “Evidence” for yes/no rules:
#     Instead of OS/services, look for polarity/trigger signals the rule likely used:
#     - explicit yes/no tokens or negations,
#     - “attached”/blank markers,
#     - rule phrases like “auto-fail”, “not applicable”, “no X”.
YESNO_EVIDENCE_PAT = re.compile(
    r"\b(yes|no|none|n/a|not applicable|blank|attached|auto[- ]?fail|fail\b|deny|do not|don'?t|cannot|is required)\b",
    re.I
)

def has_yesno_evidence(reason: str) -> bool:
    return bool(YESNO_EVIDENCE_PAT.search(str(reason)))

df_rule["has_evidence"] = df_rule["reason"].apply(has_yesno_evidence)

spec_by_label = (df_rule.groupby("predicted_compliance")["has_evidence"].mean() * 100).round(1)
print("\nSpecificity for yes/no rules (% reasons with polarity/trigger signals):")
print(spec_by_label.to_string())

# 5d. Reason length (sanity: Fail should be short & templated; others moderate)
df_rule["reason_length"] = df_rule["reason"].astype(str).str.split().str.len()
print("\nReason length per label:")
print(df_rule.groupby("predicted_compliance")["reason_length"].describe().round(2))

# ---------------------------------------------------------------------
# === 6) Sample for manual inspection ===
# ---------------------------------------------------------------------
print("\nSample closed-rule predictions with reasons:")
cols = [c for c in ["file", "question_id", "answer_text", "predicted_compliance", "reason"] if c in df_rule.columns]
try:
    display(df_rule[cols].head(10))
except NameError:
    print(df_rule[cols].head(10).to_string(index=False))


Reason coverage (rules-only): 3059/3059 (100.00%)

Coverage by predicted label:
                      total  with_reason  pct_with_reason
predicted_compliance                                     
Compliant              2921         2921            100.0
Fail                    126          126            100.0
Non-compliant            12           12            100.0

Top variability in reasons (more unique = less consistent):
question_id predicted_compliance  unique_reasons
       A1.1            Compliant               1
      A1.10            Compliant               1
      A1.10                 Fail               1
       A1.2            Compliant               1
       A1.3            Compliant               1
       A1.3                 Fail               1
       A1.4            Compliant               1
       A1.5            Compliant               1
       A1.6            Compliant               1
       A1.7            Compliant               1
       A1.8            Complia

file question_id  \
0  answers (1).pdf        A1.1   
1  answers (1).pdf       A1.10   
2  answers (1).pdf        A1.2   
3  answers (1).pdf        A1.3   
4  answers (1).pdf        A1.4   
5  answers (1).pdf        A1.5   
6  answers (1).pdf        A1.6   
7  answers (1).pdf        A1.7   
8  answers (1).pdf        A1.8   
9  answers (1).pdf        A1.9   

                                         answer_text predicted_compliance  \
0                               Albyn School Limited            Compliant   
1                                                Yes            Compliant   
2                 LTD - Limited Company (Ltd or PLC)            Compliant   
3                                           SC026743            Compliant   
4                            Country: United Kingdom            Compliant   
5  Academia - Secondary Schools\nNotes:\nApplican...            Compliant   
6                                www.albynschool.org            Compliant   
7                                    New Application            Compliant   
8  To Generally Improve Our Security\nNotes:\nSec...            Compliant   
9                                                Yes            Compliant   

                                     reason  
0  Info‑only question with non‑blank answer  
1  Info‑only question with non‑blank answer  
2  Info‑only question with non‑blank answer  
3  Info‑only question with non‑blank answer  
4  Info‑only question with non‑blank answer  
5  Info‑only question with non‑blank answer  
6  Info‑only question with non‑blank answer  
7  Info‑only question with non‑blank answer  
8  Info‑only question with non‑blank answer  
9                Answered 'Yes' (compliant)

**Reason coverage** was complete across all rule-based items, with 3,059/3,059 answers (100%) carrying an assigned justification. This shows that every closed-rule decision returned both a label and an explanation, without gaps.

**Coverage by predicted label** confirms that almost all outputs were marked Compliant (2,921 cases), with smaller counts for Fail (126) and Non-compliant (12). All categories achieved 100% reason coverage, indicating full explanation consistency.

**Variability in reasons** was minimal, with most question–label pairs generating only a single templated explanation. This reflects the deterministic nature of closed rules, where variation is neither expected nor needed. Such uniformity supports auditability but limits richness in assessor feedback.


**Specificity** checks highlight that polarity and trigger signals were well captured: 95.1% of Compliant reasons referenced yes/no or evidence markers, and Fail/Non-compliant cases achieved 100%. This demonstrates strong alignment with the binary intent of these rules.

**Reason length** patterns were stable, with Compliant explanations averaging four words, Fail slightly longer at six words (due to templated justifications), and Non-compliant consistently three words. The short, standardised phrasing confirms that rule-based outputs are concise and predictable.

**The sample predictions** illustrate this clearly: most Compliant reasons simply state that the item was answered and non-blank, while binary yes/no items return a direct justification. This is sufficient for mechanical checks but does not offer the nuanced context found in semantic-frame rules.

### **GLOBAL PATTERN MODULE PREPARATION FOR SEMANTIC FRAMES**

In [ ]:
# 🔹 Add global patterns (optional, not per-question specific)
%%writefile global_patterns.py

global_patterns = [
{"label": "TOOL", "pattern": "SentinelOne"},
{"label": "TOOL", "pattern": "Antivirus"},
{"label": "DEVICE", "pattern": "laptops"},
{"label": "DEVICE", "pattern": "servers"},
{"label": "ROLE", "pattern": "administrator"},
{"label": "ROLE", "pattern": [{"LOWER": "it"}, {"LOWER": "manager"}]},
{"label": "ROLE", "pattern": [{"LOWER": "director"}]},
{"label": "ROLE", "pattern": [{"LOWER": "head"}, {"LOWER": "of"}, {"LOWER": "it"}]},
{"label": "LOCATION", "pattern": "aberdeen"},
{"label": "LOCATION", "pattern": "glasgow"},
{"label": "LOCATION", "pattern": "bathgate"},
{"label": "LOCATION", "pattern": "elgin"},
{"label": "LOCATION", "pattern": "dundee"},
{"label": "LOCATION", "pattern": "swansea"},
{"label": "LOCATION", "pattern": "bengaluru"},
{"label": "LOCATION", "pattern": "sydney"},
{"label": "LOCATION", "pattern": "frankfurt"},
{"label": "LOCATION", "pattern": "rosyth"},
{"label": "LOCATION", "pattern": "san jose"},
{"label": "LOCATION", "pattern": "lafayette"},
{"label": "LOCATION", "pattern": "congo"},
{"label": "LOCATION", "pattern": "winchester"},
{"label": "LOCATION", "pattern": "nairobi"},
{"label": "LOCATION", "pattern": "istanbul"},
{"label": "LOCATION", "pattern": "hong kong"},
{"label": "LOCATION", "pattern": "turkey"},
{"label": "SCOPE", "pattern": "all uk offices"},
{"label": "SCOPE", "pattern": "remote"},
{"label": "SCOPE", "pattern": "hybrid"},
{"label": "SCOPE", "pattern": "buildings"},
{"label": "OS", "pattern": [{"LOWER": "windows"}, {"IS_DIGIT": True}]},
{"label": "OS", "pattern": [{"LOWER": "windows"}, {"TEXT": {"REGEX": "10|11"}}]},
{"label": "OS", "pattern": [{"LOWER": "macos"}, {"TEXT": {"REGEX": "sonoma|ventura|sequoia|monterey"}}]},
{"label": "OS", "pattern": [{"LOWER": "linux"}]},
{"label": "OS", "pattern": [{"LOWER": "ubuntu"}]},
{"label": "OS", "pattern": [{"LOWER": "mageia"}]},
{"label": "OS", "pattern": [{"LOWER": "fedora"}]},
{"label": "OS", "pattern": [{"LOWER": "android"}]},
{"label": "OS", "pattern": [{"LOWER": "ios"}]},
{"label": "OS", "pattern": [{"LOWER": "ipados"}]},
{"label": "TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "TOOL", "pattern": [{"LOWER": "sccm"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "laptop"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "desktop"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "virtual"}, {"LOWER": "desktop"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "macbook"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "surface"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "ipad"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "nuc"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "thin"}, {"LOWER": "client"}]},
{"label": "OS", "pattern": [{"LOWER": "igel"}, {"LOWER": "os"}]},
{"label": "OS", "pattern": [{"LOWER": "hp"}, {"LOWER": "thin"}, {"LOWER": "os"}]},
{"label": "OS", "pattern": [{"LOWER": "windows"}, {"IS_DIGIT": True}]},
{"label": "OS", "pattern": [{"LOWER": "linux"}]},
{"label": "OS", "pattern": [{"LOWER": "ubuntu"}]},
{"label": "TOOL", "pattern": [{"LOWER": "virtual"}, {"LOWER": "desktop"}]},
{"label": "OS", "pattern": [{"LOWER": "windows"}, {"LOWER": "server"}, {"IS_DIGIT": True}]},
{"label": "OS", "pattern": [{"LOWER": "ubuntu"}, {"TEXT": {"REGEX": "\d+\.\d+"}}]},
{"label": "OS", "pattern": [{"LOWER": "redhat"}, {"LOWER": "linux"}]},
{"label": "OS", "pattern": [{"LOWER": "rocky"}, {"LOWER": "linux"}]},
{"label": "OS", "pattern": [{"LOWER": "oracle"}, {"LOWER": "linux"}]},
{"label": "OS", "pattern": [{"LOWER": "centos"}]},
{"label": "OS", "pattern": [{"LOWER": "debian"}]},
{"label": "TOOL", "pattern": [{"LOWER": "vmware"}, {"LOWER": "esxi"}]},
{"label": "TOOL", "pattern": [{"LOWER": "hyper"}, {"LOWER": "v"}]},
{"label": "TOOL", "pattern": [{"LOWER": "proxmox"}]},
{"label": "TOOL", "pattern": [{"LOWER": "vcenter"}]},
{"label": "TOOL", "pattern": [{"LOWER": "azure"}]},
{"label": "TOOL", "pattern": [{"LOWER": "gcp"}]},
{"label": "TOOL", "pattern": [{"LOWER": "cloud"}, {"LOWER": "run"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "iphone"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "ipad"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "android"}, {"LOWER": "phone"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "tablet"}]},
{"label": "DEVICE", "pattern": [{"LOWER": "mobile"}, {"LOWER": "device"}]},
{"label": "OS", "pattern": [{"LOWER": "ios"}]},
{"label": "OS", "pattern": [{"LOWER": "ipados"}]},
{"label": "OS", "pattern": [{"LOWER": "android"}]},
{"label": "OS", "pattern": [{"LOWER": "coloros"}]},
{"label": "OS", "pattern": [{"LOWER": "magic"}, {"LOWER": "os"}]},
{"label": "OS", "pattern": [{"LOWER": "emu1"}]},
{"label": "LOCATION", "pattern": "aberdeen"},
{"label": "LOCATION", "pattern": "glasgow"},
{"label": "LOCATION", "pattern": "london"},
{"label": "LOCATION", "pattern": "coventry"},
{"label": "LOCATION", "pattern": "lichfield"},
{"label": "LOCATION", "pattern": "turkey"},
{"label": "LOCATION", "pattern": "reading"},
{"label": "LOCATION", "pattern": "zurich"},
{"label": "LOCATION", "pattern": "bangalore"},
{"label": "LOCATION", "pattern": "gurgaon"},
{"label": "LOCATION", "pattern": "virginia"},
{"label": "LOCATION", "pattern": "il"},
{"label": "DEVICE", "pattern": [{"LOWER": "router"}]},
{"label": "TOOL", "pattern": [{"LOWER": "vpn"}]},
{"label": "TOOL", "pattern": [{"LOWER": "azure"}]},
{"label": "TOOL", "pattern": [{"LOWER": "lan"}]},
{"label": "TOOL", "pattern": [{"LOWER": "wi-fi"}]},
{"label": "TOOL", "pattern": [{"LOWER": "network"}]},
{"label": "ROLE", "pattern": [{"LOWER": "home"}, {"LOWER": "worker"}]},
{"label": "ROLE", "pattern": [{"LOWER": "remote"}, {"LOWER": "worker"}]},
{"label": "ROLE", "pattern": [{"LOWER": "hybrid"}, {"LOWER": "worker"}]},
{"label": "TOOL", "pattern": [{"LOWER": "vpn"}]},
{"label": "TOOL", "pattern": [{"LOWER": "remote"}, {"LOWER": "access"}]},
{"label": "TOOL", "pattern": [{"LOWER": "fortigate"}]},
{"label": "TOOL", "pattern": [{"LOWER": "cisco"}, {"TEXT": {"REGEX": ".*"}}]},
{"label": "TOOL", "pattern": [{"LOWER": "fortigate"}]},
{"label": "TOOL", "pattern": [{"LOWER": "meraki"}]},
{"label": "TOOL", "pattern": [{"LOWER": "draytek"}]},
{"label": "TOOL", "pattern": [{"LOWER": "palo"}, {"LOWER": "alto"}]},
{"label": "TOOL", "pattern": [{"LOWER": "watchguard"}]},
{"label": "TOOL", "pattern": [{"LOWER": "juniper"}]},
{"label": "TOOL", "pattern": [{"LOWER": "tp-link"}]},
{"label": "TOOL", "pattern": [{"LOWER": "asus"}]},
{"label": "TOOL", "pattern": [{"LOWER": "bitdefender"}]},
{"label": "TOOL", "pattern": [{"LOWER": "windows"}, {"LOWER": "defender"}]},
{"label": "TOOL", "pattern": [{"LOWER": "sophos"}]},
{"label": "TOOL", "pattern": [{"LOWER": "untangle"}]},
{"label": "TOOL", "pattern": [{"LOWER": "pfsense"}]},
{"label": "TOOL", "pattern": [{"LOWER": "technicolor"}]},
{"label": "TOOL", "pattern": [{"LOWER": "vodafone"}]},
{"label": "TOOL", "pattern": [{"LOWER": "smart"}, {"LOWER": "hub"}]},
{"label": "TOOL", "pattern": [{"LOWER": "nokia"}]},
{"label": "TOOL", "pattern": [{"LOWER": "algosec"}]},
{"label": "TOOL", "pattern": [{"LOWER": "barracuda"}]},
{"label": "TOOL", "pattern": [{"LOWER": "azure"}, {"LOWER": "virtual"}, {"LOWER": "firewall"}]},
{"label": "TOOL", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "365"}]},
{"label": "TOOL", "pattern": [{"LOWER": "google"}, {"LOWER": "workspace"}]},
{"label": "TOOL", "pattern": [{"LOWER": "aws"}]},
{"label": "TOOL", "pattern": [{"LOWER": "azure"}]},
{"label": "TOOL", "pattern": [{"LOWER": "dropbox"}]},
{"label": "TOOL", "pattern": [{"LOWER": "salesforce"}]},
{"label": "TOOL", "pattern": [{"LOWER": "zendesk"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jira"}]},
{"label": "TOOL", "pattern": [{"LOWER": "github"}]},
{"label": "TOOL", "pattern": [{"LOWER": "adobe"}]},
{"label": "TOOL", "pattern": [{"LOWER": "crowdstrike"}]},
{"label": "TOOL", "pattern": [{"LOWER": "cloudflare"}]},
{"label": "TOOL", "pattern": [{"LOWER": "slack"}]},
{"label": "TOOL", "pattern": [{"LOWER": "zoom"}]},
{"label": "TOOL", "pattern": [{"LOWER": "asana"}]},
{"label": "TOOL", "pattern": [{"LOWER": "teamviewer"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jamf"}]},
{"label": "TOOL", "pattern": [{"LOWER": "xero"}]},
{"label": "TOOL", "pattern": [{"LOWER": "imperva"}]},
{"label": "TOOL", "pattern": [{"LOWER": "wiz"}]},
{"label": "TOOL", "pattern": [{"LOWER": "oracle"}, {"LOWER": "cloud"}]},
{"label": "TOOL", "pattern": [{"LOWER": "netsuite"}]},
{"label": "TOOL", "pattern": [{"LOWER": "famly"}]},
{"label": "TOOL", "pattern": [{"LOWER": "doctract"}]},
{"label": "TOOL", "pattern": [{"LOWER": "datadog"}]},
{"label": "TOOL", "pattern": [{"LOWER": "survey"}, {"LOWER": "monkey"}]},
{"label": "TOOL", "pattern": [{"LOWER": "sharepoint"}]},
{"label": "TOOL", "pattern": [{"LOWER": "onedrive"}]},
{"label": "TOOL", "pattern": [{"LOWER": "software"}, {"LOWER": "firewall"}]},
{"label": "TOOL", "pattern": [{"LOWER": "windows"}, {"LOWER": "firewall"}]},
{"label": "TOOL", "pattern": [{"LOWER": "defender"}, {"LOWER": "firewall"}]},
{"label": "TOOL", "pattern": [{"LOWER": "macos"}, {"LOWER": "firewall"}]},
{"label": "TOOL", "pattern": [{"LOWER": "bitdefender"}]},
{"label": "TOOL", "pattern": [{"LOWER": "eset"}]},
{"label": "TOOL", "pattern": [{"LOWER": "iptables"}]},
{"label": "TOOL", "pattern": [{"LOWER": "vpn"}]},
{"label": "TOOL", "pattern": [{"LOWER": "globalprotect"}]},
{"label": "TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "TOOL", "pattern": [{"LOWER": "cloudflare"}, {"LOWER": "warp"}]},
{"label": "TOOL", "pattern": [{"LOWER": "group"}, {"LOWER": "policy"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jamf"}]},
{"label": "TOOL", "pattern": [{"LOWER": "posture"}, {"LOWER": "check"}]},
{"label": "TOOL", "pattern": [{"LOWER": "roboshadow"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "mfa"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "2fa"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "multi"}, {"LOWER": "factor"}, {"LOWER": "authentication"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "trusted"}, {"LOWER": "ip"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "ip"}, {"LOWER": "restriction"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "ip"}, {"LOWER": "filter"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "geo"}, {"LOWER": "block"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "brute"}, {"LOWER": "force"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "captcha"}]},
{"label": "TOOL", "pattern": "JumpCloud"},
{"label": "TOOL", "pattern": "Meraki"},
{"label": "TOOL", "pattern": "LastPass"},
{"label": "TOOL", "pattern": "Bitwarden"},
{"label": "TOOL", "pattern": "Azure"},
{"label": "TOOL", "pattern": "Cisco"},
{"label": "TOOL", "pattern": "Fortigate"},
{"label": "ROLE", "pattern": "IT support"},
{"label": "ROLE", "pattern": [{"LOWER": "network"}, {"LOWER": "admin"}]},
{"label": "TOOL", "pattern": "Jira"},
{"label": "TOOL", "pattern": "ServiceNow"},
{"label": "TOOL", "pattern": "Firewall Register"},
{"label": "ROLE", "pattern": [{"LOWER": "ict"}, {"LOWER": "manager"}]},
{"label": "ROLE", "pattern": [{"LOWER": "security"}, {"LOWER": "director"}]},
{"label": "ROLE", "pattern": [{"LOWER": "support"}, {"LOWER": "director"}]},
{"label": "ROLE", "pattern": [{"LOWER": "senior"}, {"LOWER": "management"}]},
{"label": "ROLE", "pattern": "partner"},
{"label": "ORG", "pattern": "Gamma"},
{"label": "ORG", "pattern": "Converged Communication Solutions"},
{"label": "ORG", "pattern": "Simblox Technologies"},
{"label": "TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jamf"}]},
{"label": "TOOL", "pattern": [{"LOWER": "rmm"}]},
{"label": "TOOL", "pattern": [{"LOWER": "sccm"}]},
{"label": "TOOL", "pattern": [{"LOWER": "datto"}]},
{"label": "TOOL", "pattern": [{"LOWER": "endpoint"}, {"LOWER": "central"}]},
{"label": "TOOL", "pattern": [{"LOWER": "manageengine"}]},
{"label": "TOOL", "pattern": [{"LOWER": "crowdstrike"}]},
{"label": "TOOL", "pattern": [{"LOWER": "tanium"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "standard"}, {"LOWER": "build"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "remove"}, {"LOWER": "bloatware"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "preinstalled"}, {"LOWER": "software"}]},
{"label": "CLOUD", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "365"}]},
{"label": "CLOUD", "pattern": [{"LOWER": "cloud"}, {"LOWER": "services"}]},
{"label": "CLOUD", "pattern": [{"LOWER": "untick"}, {"LOWER": "services"}]},
{"label": "TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jamf"}]},
{"label": "TOOL", "pattern": [{"LOWER": "rmm"}]},
{"label": "TOOL", "pattern": [{"LOWER": "sccm"}]},
{"label": "TOOL", "pattern": [{"LOWER": "datto"}]},
{"label": "TOOL", "pattern": [{"LOWER": "endpoint"}, {"LOWER": "central"}]},
{"label": "TOOL", "pattern": [{"LOWER": "manageengine"}]},
{"label": "TOOL", "pattern": [{"LOWER": "crowdstrike"}]},
{"label": "TOOL", "pattern": [{"LOWER": "tanium"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "standard"}, {"LOWER": "build"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "bloatware"}, {"LOWER": "removed"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "reviewed"}, {"LOWER": "quarterly"}]},
{"label": "CLOUD", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "365"}, {"LOWER": "admin"}, {"LOWER": "portal"}]},
{"label": "CLOUD", "pattern": [{"LOWER": "cloud"}, {"LOWER": "services"}]},
{"label": "CLOUD", "pattern": [{"LOWER": "cloud"}, {"LOWER": "applications"}]},
{"label": "CLOUD", "pattern": [{"LOWER": "untick"}, {"LOWER": "services"}]},
{"label": "AUTH", "pattern": [{"LOWER": "biometric"}]},
{"label": "AUTH", "pattern": [{"LOWER": "fingerprint"}]},
{"label": "AUTH", "pattern": [{"LOWER": "faceid"}]},
{"label": "AUTH", "pattern": [{"LOWER": "windows"}, {"LOWER": "hello"}]},
{"label": "AUTH", "pattern": [{"LOWER": "touch"}, {"LOWER": "id"}]},
{"label": "AUTH", "pattern": [{"LOWER": "yubikey"}]},
{"label": "AUTH", "pattern": [{"LOWER": "password"}]},
{"label": "AUTH", "pattern": [{"LOWER": "passphrase"}]},
{"label": "AUTH", "pattern": [{"LOWER": "pin"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "mfa"}]},
{"label": "SECURITY", "pattern": [{"LOWER": "2fa"}]},
{"label": "REQUIREMENT", "pattern": [{"LOWER": "physical"}, {"LOWER": "presence"}]},
{"label": "REQUIREMENT", "pattern": [{"LOWER": "minimum"}, {"LOWER": "password"}, {"LOWER": "length"}]},
{"label": "REQUIREMENT", "pattern": [{"LOWER": "account"}, {"LOWER": "lockout"}]},
{"label": "REQUIREMENT", "pattern": [{"LOWER": "deny"}, {"LOWER": "list"}]},
{"label": "REQUIREMENT", "pattern": [{"LOWER": "password"}, {"LOWER": "complexity"}]},
{"label": "REQUIREMENT", "pattern": [{"LOWER": "unlock"}, {"LOWER": "device"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "chrome"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "google"}, {"LOWER": "chrome"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "safari"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "edge"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "edge"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "firefox"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "mozilla"}, {"LOWER": "firefox"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "opera"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "chromium"}]},
{"label": "BROWSER", "pattern": [{"LOWER": "samsung"}, {"LOWER": "internet"}]},
{"label": "VERSION", "pattern": [{"TEXT": {"REGEX": "^(\\d{2,3})(\\.\\d+)+$"}}]},
{"label": "VERSION", "pattern": [{"LOWER": "version"}, {"TEXT": {"REGEX": "^(\\d{2,3})(\\.\\d+)+$"}}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "windows"}, {"LOWER": "defender"}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "bitdefender"}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "eset"}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "sophos"}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "sentinelone"}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "crowdstrike"}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "mcafee"}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "clamav"}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "norton"}]},
{"label": "ANTIVIRUS", "pattern": [{"LOWER": "xprotect"}]},
{"label": "VERSION", "pattern": [{"TEXT": {"REGEX": "^\\d{1,3}(\\.\\d+){1,4}$"}}]},
{"label": "VERSION", "pattern": [{"LOWER": "version"}, {"TEXT": {"REGEX": "^\\d{1,3}(\\.\\d+){1,4}$"}}]},
{"label": "EMAIL_APP", "pattern": [{"LOWER": "outlook"}]},
{"label": "EMAIL_APP", "pattern": [{"LOWER": "gmail"}]},
{"label": "EMAIL_APP", "pattern": [{"LOWER": "exchange"}]},
{"label": "EMAIL_APP", "pattern": [{"LOWER": "office"}, {"LOWER": "365"}]},
{"label": "EMAIL_APP", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "365"}]},
{"label": "EMAIL_APP", "pattern": [{"LOWER": "google"}, {"LOWER": "workspace"}]},
{"label": "EMAIL_APP", "pattern": [{"LOWER": "superhuman"}]},
{"label": "EMAIL_APP", "pattern": [{"LOWER": "iphone"}, {"LOWER": "mail"}]},
{"label": "VERSION", "pattern": [{"TEXT": {"REGEX": "^\\d{1,3}(\\.\\d+){1,4}$"}}]},
{"label": "VERSION", "pattern": [{"LOWER": "version"}, {"TEXT": {"REGEX": "^\\d{1,3}(\\.\\d+){1,4}$"}}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "365"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "office"}, {"LOWER": "365"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "google"}, {"LOWER": "workspace"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "libreoffice"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "office"}, {"LOWER": "2016"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "office"}, {"LOWER": "2019"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "office"}, {"LOWER": "2021"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "office"}, {"LOWER": "2024"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "adobe"}, {"LOWER": "creative"}, {"LOWER": "cloud"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "affinity"}, {"LOWER": "publisher"}]},
{"label": "OFFICE_APP", "pattern": [{"LOWER": "netdocuments"}]},
{"label": "VERSION", "pattern": [{"TEXT": {"REGEX": "^v?\\d{2,4}(\\.\\d+)*$"}}]},
{"label": "VERSION", "pattern": [{"LOWER": "version"}, {"TEXT": {"REGEX": "^\\d{2,4}(\\.\\d+)*$"}}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "manual"}, {"LOWER": "updates"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "patching"}, {"LOWER": "schedule"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "auto"}, {"LOWER": "updates"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "weekly"}, {"LOWER": "updates"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "firmware"}, {"LOWER": "updates"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "datto"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "rmm"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "connectwise"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "patchmypc"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "solarwinds"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "appcheck"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "helpdesk"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "manual"}, {"LOWER": "intervention"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "manual"}, {"LOWER": "update"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "patch"}, {"LOWER": "management"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "ticket"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "helpdesk"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "engineer"}, {"LOWER": "assigned"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "remote"}, {"LOWER": "session"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "14"}, {"LOWER": "days"}]},
{"label": "SECURITY_PROCESS", "pattern": [{"LOWER": "update"}, {"LOWER": "installed"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "datto"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "rmm"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "connectwise"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "patchmypc"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "crowdstrike"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "jamf"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "cyrisma"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "manageengine"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "wsus"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "noc"}, {"LOWER": "team"}]},
{"label": "SECURITY_POLICY", "pattern": [{"LOWER": "no"}, {"LOWER": "unsupported"}, {"LOWER": "software"}]},
{"label": "SECURITY_POLICY", "pattern": [{"LOWER": "unsupported"}, {"LOWER": "software"}, {"LOWER": "removed"}]},
{"label": "SEGREGATION_METHOD", "pattern": [{"LOWER": "vlan"}]},
{"label": "SEGREGATION_METHOD", "pattern": [{"LOWER": "sub"}, {"LOWER": "set"}]},
{"label": "SEGREGATION_METHOD", "pattern": [{"LOWER": "firewall"}]},
{"label": "SEGREGATION_METHOD", "pattern": [{"LOWER": "segregated"}]},
{"label": "SEGREGATION_METHOD", "pattern": [{"LOWER": "proxy"}]},
{"label": "SEGREGATION_METHOD", "pattern": [{"LOWER": "network"}, {"LOWER": "separation"}]},
{"label": "SEGREGATION_METHOD", "pattern": [{"LOWER": "no"}, {"LOWER": "internet"}, {"LOWER": "access"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "jamf"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "datto"}, {"LOWER": "rmm"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "soe"}]},
{"label": "UPDATE_TOOL", "pattern": [{"LOWER": "software"}, {"LOWER": "register"}]},
{"label": "ROLE", "pattern": [{"LOWER": "hr"}]},
{"label": "ROLE", "pattern": [{"LOWER": "director"}]},
{"label": "ROLE", "pattern": [{"LOWER": "ceo"}]},
{"label": "ROLE", "pattern": [{"LOWER": "manager"}]},
{"label": "ROLE", "pattern": [{"LOWER": "line"}, {"LOWER": "manager"}]},
{"label": "ROLE", "pattern": [{"LOWER": "founder"}]},
{"label": "ROLE", "pattern": [{"LOWER": "operations"}, {"LOWER": "director"}]},
{"label": "ROLE", "pattern": [{"LOWER": "engineering"}, {"LOWER": "lead"}]},
{"label": "ROLE", "pattern": [{"LOWER": "cab"}]},
{"label": "ROLE", "pattern": [{"LOWER": "coo"}]},
{"label": "TOOL", "pattern": [{"LOWER": "servicedesk"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jira"}]},
{"label": "TOOL", "pattern": [{"LOWER": "personio"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jumpcloud"}]},
{"label": "TOOL", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "admin"}, {"LOWER": "centre"}]},
{"label": "TOOL", "pattern": [{"LOWER": "mdm"}]},
{"label": "TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "TOOL", "pattern": [{"LOWER": "sword"}]},
{"label": "TOOL", "pattern": [{"LOWER": "eskimo"}]},
{"label": "TOOL", "pattern": [{"LOWER": "adaxes"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "mfa"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "multi"}, {"LOWER": "factor"}, {"LOWER": "authentication"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "2fa"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "rate"}, {"LOWER": "limit"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "throttling"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "lockout"}, {"LOWER": "policy"}]},
{"label": "TOOL", "pattern": [{"LOWER": "smart"}, {"LOWER": "lockout"}]},
{"label": "TOOL", "pattern": [{"LOWER": "entra"}]},
{"label": "TOOL", "pattern": [{"LOWER": "bitdefender"}]},
{"label": "TOOL", "pattern": [{"LOWER": "azure"}, {"LOWER": "ad"}]},
{"label": "TOOL", "pattern": [{"LOWER": "defender"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "mfa"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "multi"}, {"LOWER": "factor"}, {"LOWER": "authentication"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "deny"}, {"LOWER": "list"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "automatic"}, {"LOWER": "blocking"}, {"LOWER": "of"}, {"LOWER": "common"}, {"LOWER": "passwords"}]},
{"label": "SECURITY_MEASURE", "pattern": [{"LOWER": "password"}, {"LOWER": "length"}]},
{"label": "POLICY", "pattern": [{"LOWER": "password"}, {"LOWER": "policy"}]},
{"label": "POLICY", "pattern": [{"LOWER": "password"}, {"LOWER": "history"}]},
{"label": "TOOL", "pattern": [{"LOWER": "entra"}]},
{"label": "TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jumpcloud"}]},
{"label": "SECURITY_PRACTICE", "pattern": [{"LOWER": "three"}, {"LOWER": "random"}, {"LOWER": "words"}]},
{"label": "SECURITY_PRACTICE", "pattern": [{"LOWER": "password"}, {"LOWER": "manager"}]},
{"label": "SECURITY_PRACTICE", "pattern": [{"LOWER": "avoid"}, {"LOWER": "common"}, {"LOWER": "passwords"}]},
{"label": "SECURITY_PRACTICE", "pattern": [{"LOWER": "password"}, {"LOWER": "training"}]},
{"label": "SECURITY_PRACTICE", "pattern": [{"LOWER": "password"}, {"LOWER": "advice"}]},
{"label": "SECURITY_PRACTICE", "pattern": [{"LOWER": "no"}, {"LOWER": "regular"}, {"LOWER": "expiry"}]},
{"label": "SECURITY_PRACTICE", "pattern": [{"LOWER": "not"}, {"LOWER": "enforcing"}, {"LOWER": "complexity"}]},
{"label": "TOOL", "pattern": [{"LOWER": "authenticator"}]},
{"label": "TOOL", "pattern": [{"LOWER": "google"}, {"LOWER": "authenticator"}]},
{"label": "TOOL", "pattern": [{"LOWER": "ms"}, {"LOWER": "authenticator"}]},
{"label": "TOOL", "pattern": [{"LOWER": "windows"}, {"LOWER": "authenticator"}]},
{"label": "TOOL", "pattern": [{"LOWER": "proton"}]},
{"label": "TOOL", "pattern": [{"LOWER": "dropbox"}]},
{"label": "TOOL", "pattern": [{"LOWER": "saml"}]},
{"label": "TOOL", "pattern": [{"LOWER": "entra"}, {"LOWER": "id"}]},
{"label": "SERVICE", "pattern": [{"LOWER": "proofpoint"}]},
{"label": "SERVICE", "pattern": [{"LOWER": "homemaster"}]},
{"label": "SERVICE", "pattern": [{"LOWER": "dropbox"}]},
{"label": "SERVICE", "pattern": [{"LOWER": "proton"}]},
{"label": "SERVICE", "pattern": [{"LOWER": "google"}, {"LOWER": "workspace"}]},
{"label": "SERVICE", "pattern": [{"LOWER": "microsoft"}, {"LOWER": "365"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "leaver"}, {"LOWER": "process"}]},
{"label": "ROLE", "pattern": [{"LOWER": "hr"}]},
{"label": "ROLE", "pattern": [{"LOWER": "line"}, {"LOWER": "manager"}]},
{"label": "TOOL", "pattern": [{"LOWER": "servicenow"}]},
{"label": "TOOL", "pattern": [{"LOWER": "helpdesk"}]},
{"label": "TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "ACTION", "pattern": [{"LOWER": "disable"}, {"LOWER": "account"}]},
{"label": "ACTION", "pattern": [{"LOWER": "delete"}, {"LOWER": "account"}]},
{"label": "POLICY", "pattern": [{"LOWER": "least"}, {"LOWER": "privilege"}]},
{"label": "TOOL", "pattern": [{"LOWER": "active"}, {"LOWER": "directory"}]},
{"label": "TOOL", "pattern": [{"LOWER": "rbac"}]},
{"label": "TOOL", "pattern": [{"LOWER": "google"}, {"LOWER": "workspace"}, {"LOWER": "groups"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "access"}, {"LOWER": "review"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "role"}, {"LOWER": "change"}]},
{"label": "ROLE", "pattern": [{"LOWER": "line"}, {"LOWER": "manager"}]},
{"label": "TOOL", "pattern": [{"LOWER": "helpdesk"}]},
{"label": "TOOL", "pattern": [{"LOWER": "itsm"}]},
{"label": "ROLE", "pattern": [{"LOWER": "it"}, {"LOWER": "manager"}]},
{"label": "ROLE", "pattern": [{"LOWER": "director"}]},
{"label": "ROLE", "pattern": [{"LOWER": "head"}, {"LOWER": "of"}, {"LOWER": "it"}]},
{"label": "ROLE", "pattern": [{"LOWER": "ciso"}]},
{"label": "TOOL", "pattern": [{"LOWER": "servicenow"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jira"}]},
{"label": "TOOL", "pattern": [{"LOWER": "helpdesk"}]},
{"label": "TOOL", "pattern": [{"LOWER": "laps"}]},
{"label": "TOOL", "pattern": [{"LOWER": "privileged"}, {"LOWER": "identity"}, {"LOWER": "management"}]},
{"label": "TOOL", "pattern": [{"LOWER": "laps"}]},
{"label": "TOOL", "pattern": [{"LOWER": "intune"}]},
{"label": "TOOL", "pattern": [{"LOWER": "pim"}]},
{"label": "TOOL", "pattern": [{"LOWER": "entra"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jamf"}]},
{"label": "TOOL", "pattern": [{"LOWER": "syncro"}]},
{"label": "TOOL", "pattern": [{"LOWER": "threatlocker"}]},
{"label": "TOOL", "pattern": [{"LOWER": "group"}, {"LOWER": "policy"}]},
{"label": "ROLE", "pattern": [{"LOWER": "head"}, {"LOWER": "of"}, {"LOWER": "technology"}]},
{"label": "ROLE", "pattern": [{"LOWER": "it"}, {"LOWER": "manager"}]},
{"label": "TOOL", "pattern": [{"LOWER": "threatlocker"}]},
{"label": "TOOL", "pattern": [{"LOWER": "pim"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jamf"}]},
{"label": "TOOL", "pattern": [{"LOWER": "syncro"}]},
{"label": "TOOL", "pattern": [{"LOWER": "entra"}]},
{"label": "TOOL", "pattern": [{"LOWER": "laps"}]},
{"label": "TOOL", "pattern": [{"LOWER": "firewall"}]},
{"label": "ROLE", "pattern": [{"LOWER": "it"}, {"LOWER": "helpdesk"}]},
{"label": "ROLE", "pattern": [{"LOWER": "cyber"}, {"LOWER": "trainer"}]},
{"label": "ROLE", "pattern": [{"LOWER": "head"}, {"LOWER": "of"}, {"LOWER": "technology"}]},
{"label": "ROLE", "pattern": [{"LOWER": "head"}, {"LOWER": "of"}, {"LOWER": "operations"}]},
{"label": "ROLE", "pattern": [{"LOWER": "it"}, {"LOWER": "helpdesk"}]},
{"label": "TOOL", "pattern": [{"LOWER": "azure"}]},
{"label": "TOOL", "pattern": [{"LOWER": "pim"}]},
{"label": "TOOL", "pattern": [{"LOWER": "rmm"}]},
{"label": "TOOL", "pattern": [{"LOWER": "psa"}]},
{"label": "TOOL", "pattern": [{"LOWER": "jumpcloud"}]},
{"label": "TOOL", "pattern": [{"LOWER": "preside"}]},
{"label": "TOOL", "pattern": [{"LOWER": "entra"}]},
{"label": "TOOL", "pattern": [{"LOWER": "whatfix"}]},
{"label": "TOOL", "pattern": [{"LOWER": "sentinel"}]},
{"label": "TOOL", "pattern": [{"LOWER": "gsd"}]},
{"label": "TOOL", "pattern": [{"LOWER": "google"}, {"LOWER": "alerts"}]},
{"label": "TOOL", "pattern": [{"LOWER": "password"}, {"LOWER": "reset"}]},
{"label": "TOOL", "pattern": [{"LOWER": "mfa"}]},
{"label": "ROLE", "pattern": [{"LOWER": "group"}, {"LOWER": "it"}]},
{"label": "ROLE", "pattern": [{"LOWER": "global"}, {"LOWER": "service"}, {"LOWER": "desk"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "lockout"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "account"}, {"LOWER": "recovery"}]},
{"label": "PROCESS", "pattern": [{"LOWER": "self"}, {"LOWER": "service"}, {"LOWER": "reset"}]},
{"label": "SCOPE", "pattern": [{"LOWER": "cssf"}, {"LOWER": "network"}]},
{"label": "SCOPE", "pattern": [{"LOWER": "production"}, {"LOWER": "network"}]},
{"label": "SCOPE", "pattern": [{"LOWER": "nairobi"}, {"LOWER": "network"}]},
]


Writing global_patterns.py


### **SEMANTIC MODULE PREPARATIONS FOR LIST-TYPE QUESTIONS**

In [ ]:
%%writefile semantic_rules.py
import spacy
from global_patterns import global_patterns
from typing import Dict
nlp = spacy.load("en_core_web_sm")
ruler = nlp.add_pipe("entity_ruler", before="ner")
ruler.add_patterns(global_patterns)

#  Per-question rule registry

# --------------------------------------------------------------------------- #
# A2.10  ―
# --------------------------------------------------------------------------- #
def rule_a2_10(text):
    import re
    doc = nlp(text)
    frame = {
        "actor": None,
        "role": None,
        "compliant": False,
        "needs_more_info": False,
        "reason":             ""

    }

    # --- Try to extract name before 'notes:' (allow lower/upper case) ---
    match = re.match(r"([a-zA-Z ,.'-]+)\s*notes:", text, re.IGNORECASE)
    if match:
        possible_name = match.group(1).strip()
        # Accept if it looks like a person (has at least two "words")
        if len(possible_name.split()) >= 2:
            frame["actor"] = possible_name

    # --- Use NER for name (if not already found) ---
    if not frame["actor"]:
        for ent in doc.ents:
            if ent.label_ == "PERSON":
                frame["actor"] = ent.text.strip()
                break

    # --- Fallback: any two-word pattern anywhere (case-insensitive) ---
    if not frame["actor"]:
        match = re.search(r"\b([a-zA-Z]+ [a-zA-Z]+)\b", text)
        if match:
            frame["actor"] = match.group(1).strip()

    # --- Role Extraction (NER then fallback) ---
    for ent in doc.ents:
        if ent.label_ == "ROLE" and not frame["role"]:
            frame["role"] = ent.text.strip()

    if not frame["role"]:
        match = re.search(r"role:\s*([a-zA-Z0-9 &\-/()]+)", text)
        if match:
            frame["role"] = match.group(1).strip()

    # --- Compliance logic ---
    lower = text.lower()
    if frame["actor"] and frame["role"]:
        frame["compliant"] = True
    elif re.search(r"(security reason|provided.*separately|phone call|central pool|iasme|not provid|see comment)", lower):
        frame["compliant"] = False
        frame["needs_more_info"] = True
    else:
        frame["compliant"] = False
        frame["needs_more_info"] = True
    # --- Reason assignment ---
    if frame["compliant"]:
        frame["reason"] = (
            f"Compliant: Name ('{frame['actor']}') and role ('{frame['role']}') identified."
        )
    elif not frame["actor"] and not frame["role"]:
        frame["reason"] = "Needs more information: Neither responsible person's name nor role identified."
    elif not frame["actor"]:
        frame["reason"] = "Needs more information: Responsible person's name not identified."
    elif not frame["role"]:
        frame["reason"] = "Needs more information: Responsible person's role not identified."
    elif re.search(r"(security reason|provided.*separately|phone call|central pool|iasme|not provid|see comment)", lower):
        frame["reason"] = "Needs more information: Applicant deferred answer or referenced out-of-band communication."
    else:
        frame["reason"] = "Needs more information: Incomplete or unclear answer."

    return frame








# --------------------------------------------------------------------------- #
# A2.2  ―
# --------------------------------------------------------------------------- #

def rule_a2_2(text: str) -> dict:
    import re
    text_l = text.lower().strip()

    frame = {
        "mentions_network_boundary": False,
        "mentions_named_subnet": False,
        "mentions_vague_geography": False,
        "mentions_teams_or_departments": False,
        "mentions_device_exclusion": False,
        "mentions_cloud_exclusion": False,
        "mentions_microsegmentation": False,
        "mentions_firewall_rule_exc": False,
        "mentions_vague_only": False,
        "mentions_company_name_only": False,
        "mentions_location_only": False,
        "mentions_product_or_project_only": False,
        "mentions_all_devices_group": False,
        "compliant": False,
        "non_compliant": False,
        "needs_more_info": False,
        "reason": ""
    }

    boundary_patterns = [
        r"\b(vlans?|subnets?)\b",
        r"\b(layer\s*[23])\b",
        r"\b(?:firewall|segmented|segregated)\b",
        r"\bscoped\s+network\b",
        r"\bproduction\s+network\b",
        r"\bnetwork\s+segment\b",
    ]
    if any(re.search(p, text_l) for p in boundary_patterns):
        frame["mentions_network_boundary"] = True

    if re.search(r"\b\w[\w\-]{2,40}\s+(?:network|vlan|subnet|segment|infrastructure|environment)\b", text_l):
        frame["mentions_named_subnet"] = True

    # ---- Improved Vague Geography/Location Handling ----
    # Geography (country/region/city) in any position, with or without "only"
    if re.search(r"\b(uk|us|europe|asia|apac|emea|americas|london|birmingham|manchester|new york|paris|tokyo)\b", text_l):
        frame["mentions_vague_geography"] = True

    # Department/team/network exclusion
    if re.search(r"\b(excluding|except)\s+(?:finance|hr|sales|marketing|legal|admin|it|support|team|production|development|network|workstations|shore operations|ships|infrastructure)\b", text_l):
        frame["mentions_teams_or_departments"] = True

    # Device-type exclusion
    if re.search(r"\b(excluding|except)\s+(?:mobile|phone|tablet|laptop|desktop|server|firewall|router|switch|pc|device)(es)?\b", text_l):
        frame["mentions_device_exclusion"] = True

    # Cloud exclusion
    if re.search(r"\b(excluding|except)\s+(?:aws|azure|gcp|cloud[- ]?services?)\b", text_l):
        frame["mentions_cloud_exclusion"] = True

    # Micro-segmentation / ACL / AD
    if re.search(r"\bmicro[- ]?seg(mentation)?\b", text_l) \
       or re.search(r"\baccess\s+control\s+lists?\b", text_l) \
       or re.search(r"\bactive\s+directory\b", text_l):
        frame["mentions_microsegmentation"] = True

    # Excluded by firewall rule
    if re.search(r"\b(excluding|except).*firewall\s+rule", text_l):
        frame["mentions_firewall_rule_exc"] = True

    # Generic "... only" with no boundary
    if re.fullmatch(r"\s*\w[\w\s\-]{0,40}\s+only\s*", text_l):
        frame["mentions_vague_only"] = True

    # All devices, vague group
    if re.search(r"\ball\s+(computers?|laptops?|servers?|firewalls?|routers?|it infrastructure)", text_l):
        frame["mentions_all_devices_group"] = True

    # Company name only (vague, single entity or Ltd/LLP/Inc etc with no network)
    if re.fullmatch(r".*\b(ltd|llp|inc|corp|plc|group|company|enterprises?)\b.*", text_l) and not frame["mentions_network_boundary"]:
        frame["mentions_company_name_only"] = True

    # Location only (city, region, address)
    if re.fullmatch(r".*\b(london|birmingham|manchester|new york|paris|tokyo|[a-zA-Z]+ office)\b.*", text_l) and not frame["mentions_network_boundary"]:
        frame["mentions_location_only"] = True

    # Product/project name only
    if re.fullmatch(r"\s*system\s*\w+\s*only\s*", text_l) or re.fullmatch(r".*project\s+\w+\s*only.*", text_l):
        frame["mentions_product_or_project_only"] = True

    disallowed_flags = [
        "mentions_vague_geography",
        "mentions_teams_or_departments",
        "mentions_device_exclusion",
        "mentions_cloud_exclusion",
        "mentions_microsegmentation",
        "mentions_firewall_rule_exc",
        "mentions_vague_only",
        "mentions_company_name_only",
        "mentions_location_only",
        "mentions_product_or_project_only",
        "mentions_all_devices_group",
    ]

    if frame["mentions_network_boundary"] and not any(frame[f] for f in disallowed_flags):
        frame["compliant"] = True
    elif any(frame[f] for f in disallowed_flags):
        frame["non_compliant"] = True
    else:
        frame["needs_more_info"] = True

    # --- Reason assignment ---
    if frame["compliant"]:
        frame["reason"] = "Compliant: Network boundary (e.g. subnet, VLAN, firewall) identified with no disallowed exclusions."
    elif frame["non_compliant"]:
        triggered = [f.replace("mentions_", "").replace("_", " ") for f in disallowed_flags if frame[f]]
        frame["reason"] = "Non-compliant: Disallowed exclusions found – " + ", ".join(triggered) + "."
    else:
        frame["reason"] = "Needs more information: No valid network boundary or disallowed exclusions identified."


    return frame










# --------------------------------------------------------------------------- #
# A2.3  ― “Describe the geographical locations of your business in‑scope”
# --------------------------------------------------------------------------- #
#   • Accept clear addresses, towns/cities, data‑centres, offices, sites.
#   • Flag obviously vague answers (“UK”, “Global”, “Online only”, blank, …).
#   • Provide a structured frame so the assessor UI can highlight gaps.
# --------------------------------------------------------------------------- #
def rule_a2_3(text: str) -> dict:
    import re
    answer = text.strip()
    doc = nlp(answer)

    frame = {
        "locations": [],
        "has_vague_location": False,
        "mentions_remote": False,
        "mentions_datacentre": False,
        "needs_more_info": True,
        "compliant": False,
        "reason": ""
    }

    # 1. spaCy NER
    LOC_LABELS = ["GPE", "LOC", "FAC", "ORG"]
    frame["locations"].extend(
        ent.text.strip() for ent in doc.ents if ent.label_ in LOC_LABELS
    )

    # 2. GeoText city extraction
    try:
        from geotext import GeoText
        geo = GeoText(answer)
        frame["locations"].extend(geo.cities)
        frame["locations"].extend(geo.country_mentions)  # Adds country names if detected
    except ImportError:
        pass

    # 3. pycountry for countries
    try:
        import pycountry
        for c in pycountry.countries:
            if c.name.lower() in answer.lower() and c.name not in frame["locations"]:
                frame["locations"].append(c.name)
        # -------- pycountry.subdivisions (UK regions) --------
        uk_subdivs = {s.name.lower() for s in pycountry.subdivisions.get(country_code="GB")}
        # Add common forms if not present
        uk_subdivs |= {"england", "wales", "scotland", "northern ireland"}
        for subdiv in uk_subdivs:
            if subdiv in answer.lower() and subdiv.title() not in frame["locations"]:
                frame["locations"].append(subdiv.title())
    except ImportError:
        pass

           # --- NEW: Always extract UK subdivisions explicitly ---
    uk_subdivisions = ["england", "wales", "scotland", "northern ireland"]
    for region in uk_subdivisions:
        if re.search(rf"\b{region}\b", answer, re.I):
            # Title case for display, e.g., "England"
            display = region.title() if region != "northern ireland" else "Northern Ireland"
            if display not in frame["locations"]:
                frame["locations"].append(display)

    # 4. Datacentre/colo regex
    dc_match = re.findall(
        r"\b(?:aws|azure|gcp|equix?|telehouse|datacentre|data\s*center)\b[\w\-\. ]*",
        answer, flags=re.I
    )
    if dc_match:
        frame["mentions_datacentre"] = True
        frame["locations"].extend([m.strip() for m in dc_match])

    # 5. Address-like
    street_like = re.findall(
        r"\b[A-Z][\w\s]{2,40}\s(?:road|street|lane|park|business\s+park|campus)\b",
        answer, flags=re.I
    )
    frame["locations"].extend(map(str.strip, street_like))

    # 6. Postcodes (UK style)
    postcodes = re.findall(r"\b[A-Z]{1,2}\d{1,2}[A-Z]?\s*\d[A-Z]{2}\b", answer)
    frame["locations"].extend(postcodes)

    # 6a. '[place] office|branch|site...'
    trailing_place_pat = r"([A-Za-z][A-Za-z0-9' \-]{1,60})\s+(?:head\s+)?(?:regional\s+)?(?:office|branch|site|premises|workplace|location|shop|store|factory|warehouse|building|facility|campus)s?"
    for match in re.findall(trailing_place_pat, answer, flags=re.I):
        frame["locations"].append(match.strip())

    # 6b. 'head office: swansea, wales.' / 'regional office: cork, ireland.'
    labelled_office_pat = r"(?:head|regional|main|uk|us)?\s*office:\s*([A-Za-z0-9' ,\-]+)"
    for match in re.findall(labelled_office_pat, answer, flags=re.I):
        parts = [p.strip() for p in match.split(",") if p.strip()]
        frame["locations"].extend(parts)

    labelled_branch_pat = r"(?:branch|site|campus):\s*([A-Za-z0-9' ,\-]+)"
    for match in re.findall(labelled_branch_pat, answer, flags=re.I):
        parts = [p.strip() for p in match.split(",") if p.strip()]
        frame["locations"].extend(parts)

    # 6c. 'in/at/from <place>'
    loc_phrases = re.findall(r"\b(?:in|at|from)\s+([A-Za-z][A-Za-z' \-]{1,40})", answer)
    vague_words = {
        "uk", "england", "scotland", "wales", "northern ireland",
        "united kingdom", "britain", "ireland", "europe", "emea", "global", "worldwide"
    }
    for loc in loc_phrases:
        if loc.strip().lower() not in vague_words:
            frame["locations"].append(loc.strip())

    # 6d. '[place] and [place]' chained after in/at (e.g., 'dunfermline and forfar')
    chain_matches = re.findall(
        r"(?:in|at|from)?\s*([A-Za-z][A-Za-z' \-]{1,40})\s+and\s+([A-Za-z][A-Za-z' \-]{1,40})",
        answer, flags=re.I
    )
    for a, b in chain_matches:
        if a.strip().lower() not in vague_words:
            frame["locations"].append(a.strip())
        if b.strip().lower() not in vague_words:
            frame["locations"].append(b.strip())

    # 6e. Manual override for common places seen in CE data
    known_uk_places = [
        "aberdeen", "perthshire", "london", "manchester", "edinburgh", "glasgow",
        "st andrews", "dunfermline", "forfar", "epsom", "surrey", "winchester",
        "newbury", "berkshire", "westhill", "newbridge", "cork", "swansea"
    ]
    for place in known_uk_places:
        if re.search(r"\b{}\b".format(re.escape(place)), answer, flags=re.I):
            frame["locations"].append(place.title())

    # Remove duplicates & blanks
    frame["locations"] = sorted(set(l for l in frame["locations"] if l))

    # Remote work
    if re.search(r"\b(remote|home[- ]?working|work\s+from\s+home|home\s+office)\b", answer, flags=re.I):
        frame["mentions_remote"] = True

    # --- VAGUE LOGIC ---
    extracted = {l.lower().strip() for l in frame["locations"]}
    if not extracted or extracted.issubset(vague_words):
        frame["has_vague_location"] = True
    else:
        frame["has_vague_location"] = False

    # --- FINAL COMPLIANCE LOGIC ---
    if frame["locations"] and not frame["has_vague_location"]:
        frame["needs_more_info"] = False
        frame["compliant"] = True
    else:
        frame["needs_more_info"] = True
        frame["compliant"] = False

    # --- Reason assignment ---
    if frame["compliant"]:
        frame["reason"] = "Compliant: Specific location(s) identified without vague or global terms."
    elif frame["has_vague_location"]:
        frame["reason"] = "Needs more information: Only vague or global location terms were found (e.g. UK, Europe)."
    else:
        frame["reason"] = "Needs more information: No valid or recognizable location identified."


    return frame














# ──────────────────────────────────────────────────────────
# A2.4  ·  Quantities & OS versions for laptops / desktops / VDI
#        → raises Auto‑Fail if unsupported or pentest OS / hypervisor
# ──────────────────────────────────────────────────────────

from typing import Dict, List
import re

DEVICE_TYPE_KEYWORDS = {
    "laptop": ["laptop", "notebook", "macbook", "latitude", "thinkpad", "ideapad", "yoga", "surface"],
    "desktop": ["desktop", "pc", "computer", "imac", "nuc"],
    "vdi": ["vdi", "virtual desktop", "azure virtual desktop"],
}
BRANDS = ["dell", "hp", "lenovo", "apple", "asus", "acer", "huawei", "macbook", "imac", "nuc", "surface"]

def infer_device_type(text: str) -> str:
    text = text.lower()
    # Direct check for laptop/desktop model names first
    if any(x in text for x in ["laptop", "notebook", "macbook", "ideapad", "yoga", "surface"]):
        return "laptop"
    if any(x in text for x in ["desktop", "pc", "imac", "nuc"]):
        return "desktop"
    if "virtual" in text or "vdi" in text:
        return "vdi"
    for brand in BRANDS:
        if brand in text:
            if brand in {"macbook", "latitude", "thinkpad", "ideapad", "yoga", "surface"}:
                return "laptop"
            if brand in {"imac", "nuc"}:
                return "desktop"
            return "other"
    return "other"

def extract_device_counts(answer: str):
    version_spans = []
    for m in re.finditer(r'\d+\.\d+(?:\.\d+)?', answer):
        version_spans.append((m.start(), m.end()))
    pattern = re.compile(r'(\d+)\s*(?:x)?\s*([\w\- ]+)', re.I)
    counts = {"laptop": 0, "desktop": 0, "vdi": 0, "other": 0}
    device_count_total = 0
    for m in pattern.finditer(answer):
        n = int(m.group(1))
        start, end = m.span(1)
        if 2000 <= n <= 2100:
            continue
        if any(start >= vstart and end <= vend for (vstart, vend) in version_spans):
            continue
        desc = m.group(2).strip().lower()
        dtype = infer_device_type(desc)
        counts[dtype] += n
        device_count_total += n
    return counts, device_count_total

def rule_a2_4(text: str) -> Dict[str, object]:
    doc = nlp(text)
    lowered = text.lower().strip()
    frame: Dict[str, object] = {
        "counts": {"laptop": 0, "desktop": 0, "vdi": 0, "other": 0},
        "device_count_total": 0,
        "os_versions": [],
        "mentions_byod": False,
        "mentions_hypervisor": False,
        "unsupported_os": False,
        "pentest_os_flag": False,
        "needs_more_info": True,
        "auto_fail": False,
        "compliant": False,
        "all_devices_supported_os": False,
        "reason": ""
    }

    # Attached → immediately compliant
    if re.search(r"\bat+ach(ed|ment)?\b", lowered):
        frame["compliant"] = True
        frame["needs_more_info"] = False
        frame["all_devices_supported_os"] = True
        frame["reason"] = "Compliant: Applicant states information is attached separately."
        return frame

    # BYOD mention (informational flag)
    if re.search(r"\b(byod|bring\s+your\s+own\s+device|personal\s+device)\b", lowered):
        frame["mentions_byod"] = True

    # Device counts
    counts, device_count_total = extract_device_counts(lowered)
    for k in frame["counts"]:
        frame["counts"][k] = counts.get(k, 0)
    frame["device_count_total"] = device_count_total

    # “All devices are … OS” heuristic
    m_all = re.search(r"\ball\s+devices\s+(?:are|running|use)\s+([\w\s\d\.]+)", lowered)
    if m_all:
        os_guess = m_all.group(1).strip()
        if os_guess:
            frame["all_devices_supported_os"] = True
            frame["os_versions"].append(os_guess)

    # OS / version extraction
    rx_bank: List[str] = [
        r"(windows\s+(?:10|11)\s+(?:pro|professional|enterprise|home|education|business)\s*(?:version\s*)?(?:\d{2,4}h\d|\d{4}|build\s*\d+))",
        r"(windows\s+server\s+\d{4}\s*(?:standard|datacentre|essentials)?)",
        r"(windows\s+(?:vista|xp|7|8(?:\.1)?))",
        r"(windows\s+\d+\.\d+\.\d+)",
        r"(mac\s?os\s+[a-z\s]+(?:\d+\.\d+(?:\.\d+)?)?)",
        r"(opensuse\s+leap\s+\d+\.\d+)",
        r"(mageia\s+linux\s+\d+)",
        r"(ubuntu\s+\d{2}\.\d{2}(?:\s+lts)?)",
        r"(debian\s+\d+)",
        r"(centos\s+(?:stream\s+)?\d+)",
        r"(android\s+\d+)",
        r"(kali\s+linux|parrot\s+os)",
        r"(esxi\s+\d+(?:\.\d+)?|hyper[-\s]?v|vmware\s+v?sphere|virtualbox)",
    ]
    os_found: List[str] = []
    for rx in rx_bank:
        os_found += re.findall(rx, lowered)

    # Standalone versions / builds
    os_found += re.findall(r'\b\d+\.\d+\.\d+\b', lowered)
    os_found += re.findall(r'\b\d+h\d+\b', lowered)
    os_found += re.findall(r'build\s*[-: ]*\d+', lowered)
    os_found += re.findall(r'\(\s*\d+\s*\)', lowered)
    os_found += re.findall(r'\b\d{5}\b', lowered)

    # macOS codenames via NER
    mac_names = {"ventura", "sonoma", "sequoia", "monterey", "big sur", "catalina"}
    for ent in doc.ents:
        if ent.label_ == "PRODUCT" and ent.text.lower() in mac_names:
            os_found.append("macos " + ent.text.lower())

    # Clean Windows 10/11: require edition + version/build
    cleaned_os = []
    for os in os_found:
        if re.match(r'windows\s+(?:10|11)\s+(?:pro|professional|enterprise|home|education|business).*?(?:\d{2,4}h\d|\d{4}|build\s*\d+)', os):
            cleaned_os.append(os)
        elif re.match(r'windows\s+(?:10|11)\b', os):
            continue
        else:
            cleaned_os.append(os)
    frame["os_versions"] = sorted(set(s.strip() for s in cleaned_os + frame["os_versions"] if s.strip()))

    # Unsupported / pentest / hypervisor flags
    unsupported_kw = {
        "windows vista", "windows xp", "windows 7", "windows 8", "windows 8.1",
        "windows 10 home 21h1", "windows 10 1607", "windows 10 1809", "windows 10 1909",
        "android 9", "macos high sierra", "macos el capitan",
    }
    pentest_kw = {"kali linux", "parrot os"}

    for os_str in frame["os_versions"]:
        l = os_str.lower()
        if any(bad in l for bad in unsupported_kw):
            frame["unsupported_os"] = True
            frame["auto_fail"] = True
        if any(pen in l for pen in pentest_kw):
            frame["pentest_os_flag"] = True
            frame["auto_fail"] = True
        if re.search(r"(hyper[-\s]?v|esxi\s+\d|vmware|virtualbox)", l):
            frame["mentions_hypervisor"] = True

    # Final label
    if frame["device_count_total"] > 0 and frame["os_versions"] and not frame["auto_fail"]:
        frame["compliant"] = True
        frame["needs_more_info"] = False
    elif frame["all_devices_supported_os"] and not frame["auto_fail"]:
        frame["compliant"] = True
        frame["needs_more_info"] = False
    else:
        frame["compliant"] = False
        frame["needs_more_info"] = True

    # Reason assignment (full coverage)
    if frame["compliant"]:
        if frame["device_count_total"] > 0 and frame["os_versions"]:
            frame["reason"] = (
                f"Compliant: Device count ({frame['device_count_total']}) with OS version(s): "
                f"{', '.join(frame['os_versions'])}."
            )
        elif frame["all_devices_supported_os"]:
            frame["reason"] = "Compliant: All devices confirmed to run supported OS."
        else:
            frame["reason"] = "Compliant: Devices and OS information are sufficient."
    elif frame["auto_fail"]:
        if frame["unsupported_os"]:
            frame["reason"] = "Auto-fail: Unsupported operating system detected (e.g., Windows 7/8, XP, or outdated macOS)."
        elif frame["pentest_os_flag"]:
            frame["reason"] = "Auto-fail: Penetration testing OS detected (e.g., Kali Linux or Parrot OS)."
        else:
            frame["reason"] = "Auto-fail: Critical unsupported configuration detected."
    else:
        if frame["device_count_total"] == 0 and not frame["os_versions"]:
            frame["reason"] = "Needs more information: No device count or OS version provided."
        elif frame["device_count_total"] == 0 and frame["os_versions"]:
            frame["reason"] = (
                f"Needs more information: OS version(s) found ({', '.join(frame['os_versions'])}) "
                f"but no device count provided."
            )
        elif frame["device_count_total"] > 0 and not frame["os_versions"]:
            frame["reason"] = (
                f"Needs more information: {frame['device_count_total']} device(s) listed but no OS version provided."
            )
        else:
            frame["reason"] = "Needs more information: Incomplete or unclear details on devices/OS."

    return frame



















# --------------------------------------------------------------------------- #
# A2.4.1  ― Thin client devices in scope
# --------------------------------------------------------------------------- #

def rule_a2_4_1(text):
    doc = nlp(text)
    text_l = text.lower().strip()

    frame = {
        "mentions_thin_clients": False,
        "quantity": 0,
        "has_os_info": False,
        "unsupported_os": False,
        "clear_no_thin_clients": False,
        "non_compliant_missing_os": False,
        "auto_fail": False,
        "compliant": False,
        "needs_more_info": True,
        "reason": ""
    }

    # --- 0 / none / n/a by itself: treat as "no thin clients" ---
    if text_l in {"0", "none", "n/a", "not applicable", "no"}:
        frame["clear_no_thin_clients"] = True
        frame["compliant"] = True
        frame["needs_more_info"] = False
        frame["reason"] = "Compliant: Applicant states no thin clients in use."
        return frame

    # Detect mention of thin clients
    if re.search(r"\bthin client(s)?\b", text_l):
        frame["mentions_thin_clients"] = True

    # Explicit "no thin clients" phrases — early exit
    no_phrases = [
        r"\bno thin clients?\b",
        r"\b(we|i)\s+(do not|don’t|dont|are not|aren't|not)\s+(have|use|using|utilise|utilizing|deploy(ed|ing)?)\b.*thin clients?",
        r"\bnone\b", r"\bn/a\b", r"\bnot applicable\b",
        r"\bno\b.*thin clients?.*in use",
        r"\bdo not utilise\b.*thin clients?",
        r"\bno.*thin client.*on the network",
        r"\bnot using thin clients?\b",
        r"\bnot.*using.*thin clients?\b",
        r"\bnot.*thin client.*environment\b"
    ]
    for pattern in no_phrases:
        if re.search(pattern, text_l):
            frame["clear_no_thin_clients"] = True
            frame["compliant"] = True
            frame["needs_more_info"] = False
            frame["reason"] = "Compliant: Explicit phrase indicates no thin clients in use."
            return frame

    # Quantity detection — only if thin clients are mentioned
    if frame["mentions_thin_clients"]:
        number_matches = re.findall(r"\b\d+\b", text_l)
        if number_matches:
            numbers = [int(n) for n in number_matches]
            frame["quantity"] = max(numbers)

    # OS detection (supported and mentioned)
    os_patterns = [
        r"windows\s+(10|11|7|8|xp|vista|iot|home|enterprise|ltsc|pro)?",
        r"ubuntu", r"linux", r"debian", r"macos", r"el capitan",
        r"android", r"chromeos", r"igel", r"hp thin os", r"parrot", r"kali"
    ]
    if any(re.search(p, text_l) for p in os_patterns):
        frame["has_os_info"] = True

    # Unsupported OS = Auto-fail
    unsupported_os_keywords = [
        "windows 7", "windows 8", "vista", "xp",
        "1809", "1607", "1903", "1909", "2004",
        "macos high sierra", "el capitan",
        "parrot", "kali",
        "android 9", "windows 10 home 21h1"
    ]
    if any(os in text_l for os in unsupported_os_keywords):
        frame["unsupported_os"] = True
        frame["auto_fail"] = True
        frame["reason"] = "Auto-fail: Unsupported OS version mentioned for thin clients."
        return frame

    # Windows 10 without safe versions (optional stricter rule)
    if re.search(r"\bwindows\s+10\b", text_l) and not re.search(r"\b(22h2|iot|enterprise|ltsc)\b", text_l):
        frame["unsupported_os"] = True
        frame["auto_fail"] = True
        frame["reason"] = "Auto-fail: Windows 10 variant without supported build specified."
        return frame

    # Flag missing OS info if thin clients are mentioned with quantity
    if frame["mentions_thin_clients"] and frame["quantity"] > 0 and not frame["has_os_info"]:
        frame["non_compliant_missing_os"] = True
        frame["needs_more_info"] = True
        frame["reason"] = "Needs more information: Thin client count provided but OS version missing."
        return frame

    # --- Final label logic ---
    if (
        frame["mentions_thin_clients"]
        and frame["quantity"] > 0
        and frame["has_os_info"]
        and not frame["auto_fail"]
        and not frame["non_compliant_missing_os"]
    ):
        frame["compliant"] = True
        frame["needs_more_info"] = False
        frame["reason"] = f"Compliant: {frame['quantity']} thin clients listed with OS information."
    elif (
        frame["mentions_thin_clients"]
        and (frame["quantity"] == 0 or not frame["has_os_info"])
        and not frame["auto_fail"]
    ):
        frame["needs_more_info"] = True
        frame["reason"] = "Needs more information: Thin clients mentioned but device count or OS info unclear."
    else:
        frame["reason"] = "Needs more information: Thin client usage not clearly stated."

    return frame










# --------------------------------------------------------------------------- #
# A2.5  ―
# --------------------------------------------------------------------------- #

from typing import Dict, List
import re

try:
    from text2num import text2num
except ImportError:
    text2num = None

def extract_all_numbers(text: str) -> List[int]:
    nums = [int(x) for x in re.findall(r"\b\d{1,4}\b", text)]
    if text2num:
        for m in re.finditer(
            r'\b(?:zero|one|two|three|four|five|six|seven|eight|nine|ten|'
            r'eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|'
            r'eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|'
            r'eighty|ninety|hundred|thousand|and|-)+\b(?:\s+\b(?:zero|one|'
            r'two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|'
            r'thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|'
            r'twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|and|-)+\b)*',
            text, re.I):
            try:
                nums.append(text2num(m.group(0)))
            except Exception:
                continue
    return nums

def rule_a2_5(text: str) -> Dict[str, object]:
    doc = nlp(text)
    lowered = text.lower().strip()

    frame: Dict[str, object] = {
        "server_count": 0,
        "hypervisor_os": [],
        "server_os": [],
        "unsupported_os": False,
        "auto_fail": False,
        "compliant": False,
        "needs_more_info": True,
        "no_servers": False,   # Explicit no/none/n/a
        "attached": False,      # Explicit attached
        "reason": ""
    }

    # 1. Mark 'attached' as compliant
    if re.search(r"\bat+ach(ed|ment)?\b", lowered):
        frame.update({
            "compliant": True,
            "needs_more_info": False,
            "attached": True,
            "reason": "Compliant: Answer refers to attached document."
        })
        return frame

    # 2. Mark negative/none answers as compliant (no servers)
    negative_phrases = [
        r"\bno servers?\b", r"\bnone\b", r"\bn/a\b", r"\bnot applicable\b",
        r"\bdo not use servers?\b", r"\bwe do not use servers?\b",
        r"\bno virtual servers?\b", r"\bno physical servers?\b",
        r"\bno servers? used\b", r"\bdo not have any servers?\b",
        r"\bwe currently do not have any servers?\b",
        r"\bwe don't use servers?\b", r"\bthere are none\b",
        r"\bnone used\b",
        r"\bjust laptops?\b", r"\bonly laptops?\b", r"\bjust desktops?\b", r"\bonly desktops?\b",
        r"\bi don't have any servers\b", r"\bthere (are|is) none\b", r"\bonly\b.*\blaptop[s]?\b", r"\bjust\b.*\blaptop[s]?\b"
    ]
    if any(re.search(p, lowered) for p in negative_phrases) or lowered.strip() in {"0", "none"}:
        frame.update({
            "compliant": True,
            "needs_more_info": False,
            "no_servers": True,
            "reason": "Compliant: Applicant clearly states that no servers are in use."
        })
        return frame

    # 3. Handle cloud servers: treat as at least one if plural and OS present
    if re.search(r"\bcloud servers?\b", lowered) and (
        re.search(r"windows server|ubuntu|linux|centos|redhat|debian", lowered)
    ):
        frame.update({
            "server_count": 1,
            "compliant": True,
            "needs_more_info": False,
            "reason": "Compliant: Cloud server(s) mentioned with valid OS."
        })
        # Continue to OS extraction below

    # 4. Server Count Extraction (robust)
    count = 0
    count_patterns = [
        r"((?:\d+|zero|one|two|three|four|five|six|seven|eight|nine|ten|"
        r"eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|"
        r"thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand)+)\s*(?:x\s*)?"
        r"(?:dell|hp|microsoft|ubuntu|linux|rocky|oracle|redhat|rhel|centos)?\s*"
        r"(?:windows\s+server\s+\d{4}|windows\s+\d{4}|linux)?\s*"
        r"(servers?|vms?|instances?|machines?)",
        r"((?:\d+|zero|one|two|three|four|five|six|seven|eight|nine|ten|"
        r"eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|"
        r"thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand)+)\s*(?:x\s*)?(standard_b\d+ms)"
    ]

    for pattern in count_patterns:
        for match in re.findall(pattern, lowered):
            num = match[0] if isinstance(match, tuple) else match
            try:
                count += int(num)
            except ValueError:
                if text2num:
                    try:
                        count += text2num(num)
                    except Exception:
                        continue
    # Fallback: scan for all numbers (avoid years)
    if count == 0:
        for n in extract_all_numbers(lowered):
            if 2000 <= n <= 2100:  # ignore years
                continue
            count += n
    frame["server_count"] = count

    # 5. OS / Hypervisor Extraction (robust)
    os_patterns = [
        r"(windows server \d{4}(?: [a-z]+)?)",
        r"(windows \d{4}(?: [a-z]+)?)",
        r"(ubuntu \d{2}\.\d{2})", r"(debian \d+)",
        r"(redhat(?: enterprise)? linux \d+)", r"(centos \d+)", r"(oracle linux \d+)",
        r"(rocky linux \d+)",
        r"\(\s*\d+\s*\)", r"build\s*[-: ]*\d+", r"\b\d{5}\b"
    ]
    hypervisor_patterns = [
        r"(vmware esxi \d+\.\d+)", r"\b(hyper[- ]?v)\b", r"(proxmox)",
        r"(azure)", r"(gcp)", r"(aws)", r"(cloud run)", r"(vcenter)",
        r"\bstandard_b\d+[a-z]*\b"
    ]
    server_os = []
    for pattern in os_patterns:
        server_os += [m for m in re.findall(pattern, lowered)]

    # Windows Server year patterns (allow "server 2016", "2019", "2022")
    if not server_os:
        for yr in ("2016", "2019", "2022"):
            if re.search(rf"server\s*{yr}", lowered) or re.search(rf"\b{yr}\b", lowered):
                server_os.append(f"windows server {yr}")

    # Add standalone version/build numbers
    server_os += re.findall(r'\b\d+\.\d+\.\d+\b', lowered)    # e.g. 10.0.19045
    server_os += re.findall(r'\b\d+h\d+\b', lowered)          # e.g. 2h32, 22h2
    server_os += re.findall(r'\b\d{4}h\d\b', lowered)         # e.g. 1123h2, 1022h2

    # spaCy mac product names (if your org uses non-Windows servers)
    mac_names = {"ventura", "sonoma", "sequoia", "monterey", "big sur", "catalina"}
    for ent in doc.ents:
        if ent.label_ == "PRODUCT" and ent.text.lower() in mac_names:
            server_os.append("macos " + ent.text.lower())

    frame["server_os"] = sorted(set(s.strip() for s in server_os if s.strip()))

    # --- Hypervisors ---
    hypervisors = []
    for pattern in hypervisor_patterns:
        for match in re.findall(pattern, lowered):
            hypervisors.append(match.strip())
    if "azure" in lowered and "azure" not in hypervisors:
        hypervisors.append("azure")
    frame["hypervisor_os"] = sorted(set(hypervisors))

    # 6. Unsupported/Pentest OS detection
    unsupported_keywords = [
        "windows server 2008", "windows server 2012", "windows 7", "windows 8",
        "centos 6", "centos 7", "oracle linux 6", "esxi 6.5", "parrot", "kali", "rhel 6"
    ]
    for keyword in unsupported_keywords:
        if keyword in lowered:
            frame["unsupported_os"] = True
            frame["auto_fail"] = True
            break
    for os_version in frame["server_os"]:
        if any(u in os_version.lower() for u in unsupported_keywords):
            frame["unsupported_os"] = True
            frame["auto_fail"] = True
            break

    # 7. Final Compliance / MIR logic
    # Compliant if servers listed and OS/hypervisor, not auto-fail
    if (
        frame["server_count"] > 0 and
        (frame["server_os"] or frame["hypervisor_os"]) and
        not frame["auto_fail"]
    ):
        frame["compliant"] = True
        frame["needs_more_info"] = False
        frame["reason"] = f"Compliant: {frame['server_count']} server(s) listed with OS or hypervisor information."

    elif not frame["auto_fail"]:
        frame["compliant"] = False
        frame["needs_more_info"] = True
        if frame["server_count"] == 0:
            frame["reason"] = "Needs more information: No server count could be determined."
        elif not (frame["server_os"] or frame["hypervisor_os"]):
            frame["reason"] = "Needs more information: Server(s) listed but missing OS or hypervisor info."
        else:
            frame["reason"] = "Needs more information: Server data incomplete or unclear."

    # --- Auto-fail block ---
    if frame["auto_fail"]:
        if frame["unsupported_os"]:
            frame["reason"] = "Auto-fail: Unsupported server OS or configuration detected."
        else:
            frame["reason"] = "Auto-fail: Critical unsupported software or environment detected."

    return frame














# --------------------------------------------------------------------------- #
# A2.6 — “Quantities of tablets / mobiles in scope”
# --------------------------------------------------------------------------- #
from typing import List, Dict
import re

try:
    from text2num import text2num
except ImportError:
    text2num = None

def extract_all_numbers(text: str) -> List[int]:
    nums = [int(x) for x in re.findall(r"\b\d{1,4}\b", text)]
    if text2num:
        for m in re.finditer(
            r'\b(?:zero|one|two|three|four|five|six|seven|eight|nine|ten|'
            r'eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|'
            r'eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|'
            r'eighty|ninety|hundred|thousand|and|-)+\b(?:\s+\b(?:zero|one|'
            r'two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|'
            r'thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|'
            r'twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|and|-)+\b)*',
            text, re.I):
            try:
                nums.append(text2num(m.group(0)))
            except Exception:
                continue
    return nums

def rule_a2_6(text: str) -> Dict[str, object]:
    """
    Returns a frame describing the applicant’s answer to A2.6 (mobile/tablet OS).
    """
    doc = nlp(text)
    lower = text.lower().strip()
    frame: Dict[str, object] = {
        "mobile_device_count": 0,
        "os_versions":        [],
        "unsupported_os":     False,
        "auto_fail":          False,
        "compliant":          False,
        "needs_more_info":    False,
        "non_compliant":      False,
        "mentions_byod":      False,
        "attached":           False,
        "no_devices":         False,
        "reason":             ""
    }

    # 1. "Attached" shortcut
    if re.search(r"\bat+ach(ed|ment)?\b", lower):
        frame["compliant"] = True
        frame["attached"] = True
        frame["reason"] = "Compliant: Applicant refers to an attached inventory of mobile/tablet devices."
        return frame

    # 2. Explicit negative/none patterns
    NEG_PATTERNS = [
        r"\bno (mobiles?|tablets?|devices?|iphones?|ipads?)\b",
        r"\bnone\b",
        r"\bn/a\b",
        r"\bnot applicable\b",
        r"\bdo not use\b.*(mobile|tablet|device|phone|ipad|iphone)s?",
        r"\bdo not have\b.*(mobile|tablet|device|phone|ipad|iphone)s?",
        r"\bwe do not use\b.*(mobile|tablet|device|phone|ipad|iphone)s?",
        r"\bwe do not have\b.*(mobile|tablet|device|phone|ipad|iphone)s?",
        r"\bnot using\b.*(mobile|tablet|device|phone|ipad|iphone)s?",
        r"\bno company mobile\b",
        r"\bno company tablet\b",
        r"\bno company device\b",
        r"\bnot in use\b",
        r"\bno one allowed\b.*(mobile|tablet|device|phone|ipad|iphone)s?",
        r"\bno byod\b",
        r"\bnot used\b",
        r"\bthere (are|is) none\b",
        r"\bnone used\b"
    ]
    if any(re.search(p, lower) for p in NEG_PATTERNS) or lower in {"0", "none"}:
        frame["compliant"] = True
        frame["no_devices"] = True
        frame["reason"] = "Compliant: Applicant explicitly states no mobile or tablet devices are in use."
        return frame

    # 3. BYOD mention
    if re.search(r"\b(byod|bring\s+your\s+own\s+device|personal\s+device)\b", lower):
        frame["mentions_byod"] = True

    # 4. Device-count extraction
    norm = re.sub(r"(\d+)\s*[\*x×]\s*", r"\1 ", lower)
    device_count = 0
    for m in re.finditer(r"\b\d{1,4}\b", norm):
        start, end = m.span()
        if re.match(r"\.\d", norm[end:end+2]) or re.match(r"\d+\.", norm[max(0, start-2):start]):
            continue
        preceding = norm[max(0, start-10):start]
        if re.search(r"(samsung|iphone|apple|huawei|android|pixel|nokia|sony|oneplus|xiaomi|oppo|vivo|motorola|lg|htc)s?\s*$", preceding):
            continue
        device_count += int(m.group())
    device_count += sum(extract_all_numbers(lower))
    frame["mobile_device_count"] = device_count

    # 5. OS detection
    OS_PATTERNS: List[str] = [
        r"\b(android)[^\d\n]{0,10}(\d{1,2}(?:\.\d+){0,2})",
        r"\b(ios|ipados)[^\d\n]{0,10}(\d{1,2}(?:\.\d+){0,2})",
        r"\b(coloros|oxygen\s?os|one\sui)[^\d\n]{0,10}(\d{1,2}(?:\.\d+){0,2})",
    ]
    os_found: List[str] = []
    for pat in OS_PATTERNS:
        for name, ver in re.findall(pat, lower):
            os_found.append(f"{name.strip()} {ver.strip()}")
            try:
                major = int(ver.split(".")[0])
                if (name == "android" and major <= 8) or (name in {"ios", "ipados"} and major <= 12):
                    frame["unsupported_os"] = True
            except Exception:
                continue

    os_found += re.findall(r'\b\d+\.\d+\.\d+\b', lower)
    os_found += re.findall(r'\b\d+h\d+\b', lower)
    os_found += re.findall(r'build\s*[-: ]*\d+', lower)
    os_found += re.findall(r'\(\s*\d+\s*\)', lower)
    os_found += re.findall(r'\b\d{5}\b', lower)

    mac_names = {"ventura", "sonoma", "sequoia", "monterey", "big sur", "catalina"}
    for ent in doc.ents:
        if ent.label_ == "PRODUCT" and ent.text.lower() in mac_names:
            os_found.append("macos " + ent.text.lower())

    frame["os_versions"] = sorted(set(s.strip() for s in os_found if s.strip()))

    # 7. Auto-fail for unsupported OS
    if frame["unsupported_os"]:
        frame["auto_fail"] = True

    # 8. Compliance logic
    if frame["auto_fail"]:
        frame["non_compliant"] = True
    elif frame["mobile_device_count"] > 0 and frame["os_versions"]:
        frame["compliant"] = True
    elif not frame["mobile_device_count"] and not frame["os_versions"]:
        frame["needs_more_info"] = True
    else:
        frame["needs_more_info"] = True

    # Exclusivity fix
    if frame["compliant"]:
        frame["needs_more_info"] = frame["non_compliant"] = False
    elif frame["needs_more_info"]:
        frame["compliant"] = frame["non_compliant"] = False
    else:
        frame["compliant"] = frame["needs_more_info"] = False

    # --- Reason assignment ---
    if frame["compliant"]:
        frame["reason"] = f"Compliant: {frame['mobile_device_count']} mobile device(s) listed with supported OS version(s)."
    elif frame["auto_fail"]:
        frame["reason"] = "Auto-fail: Unsupported OS version detected for mobile/tablet device (e.g. Android ≤8 or iOS ≤12)."
    elif frame["no_devices"]:
        frame["reason"] = "Compliant: Applicant explicitly states no mobile or tablet devices are in use."
    elif frame["attached"]:
        frame["reason"] = "Compliant: Applicant refers to an attached device inventory for mobiles/tablets."
    elif frame["mobile_device_count"] == 0 and not frame["os_versions"]:
        frame["reason"] = "Needs more information: No device count or OS version found in the answer."
    elif frame["mobile_device_count"] > 0 and not frame["os_versions"]:
        frame["reason"] = f"Needs more information: {frame['mobile_device_count']} device(s) found, but no OS version provided."
    elif not frame["mobile_device_count"] and frame["os_versions"]:
        frame["reason"] = f"Needs more information: OS version(s) mentioned ({', '.join(frame['os_versions'])}), but no device count identified."
    else:
        frame["reason"] = "Needs more information: Answer incomplete or unclear regarding mobile devices and OS."

    return frame














# --------------------------------------------------------------------------- #
# A2.7 – "List the networks in scope"
# --------------------------------------------------------------------------- #
#  Marking-guide highlights:
#   • Expect short descriptive names (“Head Office LAN”, “Prod network”, “Guest Wi-Fi”).
#   • Do NOT require IP ranges etc.
#   • Home-worker locations are *not required*; if the answer only lists home wifi,
#     prompt for clarification.
#   • If unclear / blank → assessor must request more info.
# --------------------------------------------------------------------------- #
from typing import List, Dict
import re

try:
    from text2num import text2num, NumberException
except ImportError:
    text2num = None

def extract_all_numbers(text: str) -> List[int]:
    nums = [int(x) for x in re.findall(r"\b\d{1,4}\b", text)]
    if text2num:
        for m in re.finditer(
            r'\b(?:zero|one|two|three|four|five|six|seven|eight|nine|ten|'
            r'eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|'
            r'eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|'
            r'eighty|ninety|hundred|thousand|and|-)+\b(?:\s+\b(?:zero|one|'
            r'two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|'
            r'thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|'
            r'twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|and|-)+\b)*',
            text, re.I):
            try:
                num = text2num(m.group(0))
                nums.append(num)
            except Exception:
                continue
    return nums

def rule_a2_7(text: str) -> Dict[str, object]:
    """
    Parse A2.7 (network scope listing): extracts numbers, locations, purpose, and compliance.
    """
    doc = nlp(text)
    lowered = text.lower()

    frame = {
        "network_count": 0,
        "network_locations": [],
        "purpose": [],
        "scope_unclear": False,
        "needs_more_info": False,
        "compliant": False,   # Final compliance label
        "reason": ""
    }

    # --- Extract numbers (digit and textual) ---
    all_numbers = extract_all_numbers(text)
    frame["network_count"] = max(all_numbers) if all_numbers else 0

    # --- Location extraction using spaCy and fallback ---
    locations = set()
    for ent in doc.ents:
        if ent.label_ in {"GPE", "LOC", "FAC", "ORG", "FACILITY", "LOCATION"}:
            locations.add(ent.text.strip())

    fallback_patterns = [
        r"\b[A-Z][a-z]+\s+(road|street|lane|office|building|suite|park)\b",
        r"\b(head office|main office|branch office)\b",
        r"\b[a-zA-Z]+,?\s+[A-Z]{2,3}\b",
        r"\b(uk|kenya|nairobi|aberdeen|scotland|england|wales|ireland|europe|africa)\b",
        r"\bdatacentre\b", r"\bdatacenter\b"
    ]
    for pat in fallback_patterns:
        for match in re.findall(pat, text, flags=re.I):
            if isinstance(match, tuple):
                locations.add(match[0].strip())
            else:
                locations.add(match.strip())
    frame["network_locations"] = sorted(locations)

    # --- Purpose extraction ---
    purpose_patterns = {
        "administrative": r"\b(admin|administrative)\b",
        "development": r"\b(dev|development|testing)\b",
        "home working": r"\b(home|remote|wfh|work\s+from\s+home)\b",
        "vpn": r"\bvpn\b",
        "cloud": r"\b(azure|aws|gcp|cloud)\b",
        "datacentre": r"\b(datacentre|datacenter)\b",
    }
    purposes = set()
    for label, pattern in purpose_patterns.items():
        if re.search(pattern, lowered):
            purposes.add(label)
    frame["purpose"] = sorted(purposes)

    # --- Unclear/needs more info logic ---
    if (frame["network_count"] == 0 and
        not frame["network_locations"] and
        not frame["purpose"]):
        frame["scope_unclear"] = True
        frame["needs_more_info"] = True

    # --- Final compliance label ---
    # Mark as compliant if at least one network described (by name/count) AND at least one location or purpose AND not scope_unclear
    if (
        (frame["network_count"] > 0 or frame["network_locations"] or frame["purpose"]) and
        not frame["scope_unclear"] and
        not frame["needs_more_info"]
    ):
        frame["compliant"] = True

    # --- Reason assignment ---
    if frame["compliant"]:
        parts = []
        if frame["network_count"]:
            parts.append(f"{frame['network_count']} network(s) listed")
        if frame["network_locations"]:
            parts.append(f"location(s): {', '.join(frame['network_locations'])}")
        if frame["purpose"]:
            parts.append(f"purpose(s): {', '.join(frame['purpose'])}")
        frame["reason"] = "Compliant: " + "; ".join(parts) + "."
    elif frame["scope_unclear"]:
        frame["reason"] = "Needs more information: No clear network count, location, or purpose provided."
    else:
        frame["reason"] = "Needs more information: Partial scope information detected; clarification required."

    return frame







# --------------------------------------------------------------------------- #
# A2.7.1 – "List the networks in scope"
# --------------------------------------------------------------------------- #
from typing import List, Dict
import re

try:
    from text2num import text2num, NumberException
except ImportError:
    text2num = None

def extract_all_numbers(text: str) -> List[int]:
    nums = [int(x) for x in re.findall(r"\b\d{1,4}\b", text)]
    if text2num:
        for m in re.finditer(
            r'\b(?:zero|one|two|three|four|five|six|seven|eight|nine|ten|'
            r'eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|'
            r'eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|'
            r'eighty|ninety|hundred|thousand|and|-)+\b(?:\s+\b(?:zero|one|'
            r'two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|'
            r'thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|'
            r'twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|and|-)+\b)*',
            text, re.I):
            try:
                nums.append(text2num(m.group(0)))
            except Exception:
                continue
    return nums

def rule_a2_7_1(text: str) -> Dict[str, object]:
    """
    Parse answer for home/remote worker count & handle clear “no/none/zero” as compliant.
    """
    import spacy
    nlp = spacy.load("en_core_web_sm")  # keep as-is if not loaded elsewhere

    low = (text or "").lower().strip()
    doc = nlp(text or "")

    frame: Dict[str, object] = {
        "home_worker_count": 0,
        "hybrid_or_remote":  False,
        "no_home_workers":   False,
        "compliant":         False,
        "needs_more_info":   False,
        "non_compliant":     False,
        "auto_fail":         False,
        "reason":            ""
    }

    # --- 0) Blank → auto-fail + reason ---
    if low == "":
        frame["auto_fail"] = True
        frame["needs_more_info"] = False
        frame["reason"] = "Auto-fail: Blank or missing answer text."
        return frame

    # --- 1) No/none/nil/zero phrases (NOPHRASE LOGIC) ---
    NOPHRASES = [
        r"^(none|0|zero|nil)\s*$",
        r"\b(no|none|nil|0|zero)\s+(home|remote)\s*workers?\b",
        r"\b(do not|don't|dont|never)\s+(have|permit|allow|use|employ)\b.*(home|remote)\s*workers?",
        r"\b(no|none|nil|zero|0)\s+(remote|home)?\s*working\b",
        r"\bno\s+employees\b",
        r"\bnot\s+applicable\b",
        r"\bn/a\b"
    ]
    if any(re.search(p, low) for p in NOPHRASES):
        frame["no_home_workers"] = True
        frame["compliant"] = True
        frame["reason"] = "Compliant: Applicant clearly states no home or remote workers."
        return frame

    # --- 2) Count extraction (if not a nophrase) ---
    nums = extract_all_numbers(low)
    # fallback: single-word numbers via spaCy
    WORD2NUM = {"zero":0,"one":1,"two":2,"three":3,"four":4,"five":5,"six":6,"seven":7,"eight":8,"nine":9,"ten":10}
    for tok in doc:
        n = WORD2NUM.get(tok.lower_)
        if n is not None:
            nums.append(n)

    if nums:
        frame["home_worker_count"] = max(nums)
        # detect remote/hybrid keywords
        if re.search(r"\b(remote|home[- ]?working|wfh|telecommut(e|ing)|hybrid)\b", low):
            frame["hybrid_or_remote"] = True

    # Any wording implying remote work, even without a number
    if re.search(r"\b(hybrid|remote|wfh|work\s+from\s+home|flexible\s+working|vpn)\b", low):
        frame["hybrid_or_remote"] = True

    # --- 3) Consistency & label logic ---
    contradiction = frame["no_home_workers"] and (frame["home_worker_count"] > 0 or frame["hybrid_or_remote"])
    if contradiction:
        frame["non_compliant"] = True
    elif frame["no_home_workers"]:
        frame["compliant"] = True
    elif frame["home_worker_count"] > 0 or frame["hybrid_or_remote"]:
        frame["compliant"] = True
    else:
        frame["needs_more_info"] = True

    # --- 4) Reason assignment (full coverage) ---
    if frame["non_compliant"]:
        frame["reason"] = (
            "Non-compliant: Contradiction — answer states no home workers but also mentions "
            "remote/hybrid work or provides a count."
        )
    elif frame["compliant"]:
        if frame["no_home_workers"]:
            frame["reason"] = "Compliant: Applicant clearly states no home or remote workers."
        elif frame["home_worker_count"] > 0:
            frame["reason"] = f"Compliant: {frame['home_worker_count']} home or remote workers identified."
        elif frame["hybrid_or_remote"]:
            frame["reason"] = "Compliant: Remote or hybrid working arrangement described."
        else:
            frame["reason"] = "Compliant: Answer confirms acceptable remote work configuration."
    elif frame["needs_more_info"]:
        frame["reason"] = "Needs more information: No clear statement about home/remote workers or arrangements."
    else:
        # Safety fallback (should not occur)
        frame["reason"] = "Needs more information: Insufficient detail to determine scope."

    return frame











# -------------------------------------------------------------------------
#  A2.8 – Network‑boundary equipment (firewalls / routers) checker
# -------------------------------------------------------------------------
#  • Extract make‑and‑model strings with a single regex bank + spaCy fallback
#  • Distinguish between   →   hardware / virtual / “software‑only” firewalls
#  • Auto‑fail if an EOL / unsupported device is mentioned
#  • Final tri‑state labels:   compliant / needs_more_info / non_compliant_auto_fail
# -------------------------------------------------------------------------

from typing import List, Dict
import re

UNSUPPORTED_MODELS = {
    # Cisco
    "asa5505", "cisco 887", "ciscoc887",
    # Home / ISP kit
    "bt homehub 3", "smart hub 1", "bthub 1", "bt voyager 2100",
    "thomson tg585", "d-link dir-615", "tp-link wr841n",
    # Old DrayTeks
    "draytek 2830",
    # Hypervisor version EOL
    "esxi 6.5",
    # Ancient OS examples
    "windows xp",
}

# Expanded vendor/model regex patterns (include more brands & generic patterns)
VENDOR_PATTERNS: List[str] = [
    r"(cisco\s+\w[\w\-]+)",                      # Cisco
    r"(forti(?:gate|net)\s+\w[\w\-]+)",          # Fortinet
    r"(meraki\s+\w[\w\-]+)",                     # Meraki
    r"(draytek\s+\w[\w\-]+)",                    # Draytek
    r"(palo[\s\-]*alto\s+pa[\-\w]+)",            # Palo Alto
    r"(juniper\s+\w[\w\-]+)",                    # Juniper
    r"(watchguard\s+\w[\w\-]+)",                 # Watchguard
    r"((?:sophos|barracuda)\s+\w[\w\-]+)",       # Sophos/Barracuda
    r"((?:tp[\-\s]?link|asus|netgear)\s+\w[\w\-]+)",    # TP-Link, ASUS, Netgear
    r"(\w+\s+(?:firewall|router|gateway|hub|modem)\b[\w\-]*)",  # Generic: e.g., "sky broadband router", "vodafone wifi hub"
    r"(\w+\s+unifi\s+\w[\w\-]+)",                        # Unifi Switches
    r"(sonicwall\s+\w[\w\-]+)",                  # Sonicwall
    r"(linksys\s+\w[\w\-]+)",                    # Linksys
    r"([\w\-]+(?:firewall|router|hub|gateway|modem)[\w\-]*)",   # e.g., "smart5ghub3"
]

SOFT_FW_REGEX = re.compile(
    r"(software|virtual|cloud[- ]?(based)?)\s+(firewall|gateway)|"
    r"(windows defender|bitdefender|intune|gravityzone|untangle|pfsense|mcafee|azure virtual firewall|windows firewall|sophos endpoint|gravityzone)",
    re.I,
)

def rule_a2_8(text: str) -> Dict[str, object]:
    low = text.lower()
    frame: Dict[str, object] = {
        "device_models":          [],   # unique make‑and‑model strings
        "software_firewall_only": False,
        "unsupported_device_flag": False,
        "auto_fail":              False,
        "compliant":              False,
        "needs_more_info":        False,
        "reason":            ""
    }

    found: List[str] = []
    for rx in VENDOR_PATTERNS:
        found.extend(re.findall(rx, text, flags=re.I))

    # spaCy fallback for PRODUCT, ORG, and any sentence with "firewall", "router", etc.
    for ent in nlp(text).ents:
        if ent.label_ in {"PRODUCT", "ORG"}:
            sent = ent.sent.text.lower()
            if any(w in sent for w in ("firewall", "router", "gateway", "hub", "switch", "modem")):
                found.append(ent.text)

    # Remove whitespace/double spaces/normalize models
    found = {re.sub(r"\s{2,}", " ", f.strip(" .,-:")) for f in found if f.strip()}
    frame["device_models"] = sorted(found)

    # Is it software/virtual firewall only?
    frame["software_firewall_only"] = bool(SOFT_FW_REGEX.search(low))

    # Unsupported/EOL device triggers auto_fail
    for bad in UNSUPPORTED_MODELS:
        if bad in low:
            frame["unsupported_device_flag"] = True
            frame["auto_fail"] = True
            break

    # If nothing hardware-like found, needs more info (unless at least a generic keyword exists)
    if not frame["device_models"]:
        if not re.search(r"\b(firewall|router|gateway|hub|modem)\b", low):
            frame["needs_more_info"] = True
    else:
        # If only software, still "needs_more_info" unless model AND hardware found
        if frame["software_firewall_only"]:
            frame["needs_more_info"] = True
        else:
            frame["compliant"] = True

    # If auto_fail, override label
    if frame["auto_fail"]:
        frame["compliant"] = False
        frame["needs_more_info"] = False

    # --- Reason assignment ---
    if frame["auto_fail"]:
        frame["reason"] = "Auto-fail: Unsupported or end-of-life firewall device detected in response."
    elif frame["compliant"]:
        frame["reason"] = f"Compliant: Supported hardware firewall device(s) identified — {', '.join(frame['device_models'])}."
    elif frame["software_firewall_only"]:
        frame["reason"] = "Needs more information: Only software or cloud-based firewall mentioned; no hardware model identified."
    elif not frame["device_models"]:
        frame["reason"] = "Needs more information: No identifiable firewall, router, or gateway device model provided."
    else:
        frame["reason"] = "Needs more information: Hardware firewall model unclear or incomplete."

    return frame








# ------------------------------------------------------------------ #
#  A2.9 – “List all 3rd‑party Cloud Services in use”
# ------------------------------------------------------------------ #
def rule_a2_9(text: str) -> Dict[str, object]:
    doc = nlp(text)
    low = text.lower()

    frame: Dict[str, object] = {
        "cloud_services":     [],               # normalised names
        "service_types":      {"saas": [], "paas": [], "iaas": []},
        "missing_cloud_flag": False,
        "compliant":          False,
        "needs_more_info":    False,
        "non_compliant_missing": False,
        "reason":             ""
    }

    KNOWN_CLOUD = {
        # -------- SaaS --------
        "microsoft 365":     "saas",
        "ms365":             "saas",
        "office 365":        "saas",
        "microsoft onedrive":"saas",
        "onedrive":          "saas",
        "google workspace":  "saas",
        "google drive":      "saas",
        "gdrive":            "saas",
        "dropbox":           "saas",
        "exchange online":   "saas",
        "outlook online":    "saas",
        "salesforce":        "saas",
        "slack":             "saas",
        "zoom":              "saas",
        "github":            "saas",
        "gitlab":            "saas",
        "jira":              "saas",
        "zendesk":           "saas",
        "hubspot":           "saas",
        "xero":              "saas",
        # -------- PaaS --------
        "azure app service":         "paas",
        "aws elastic beanstalk":     "paas",
        "heroku":                    "paas",
        "google app engine":         "paas",
        "oracle cloud functions":    "paas",
        "cloud run":                 "paas",
        # -------- IaaS --------
        "azure":             "iaas",
        "azure ad":          "iaas",
        "aws":               "iaas",
        "amazon web services":"iaas",
        "amazon ec2":        "iaas",
        "s3":                "iaas",
        "gcp":               "iaas",
        "google cloud platform":"iaas",
        "google compute engine":"iaas",
        "ibm cloud":         "iaas",
        "oracle cloud":      "iaas",
        "digitalocean":      "iaas",
        "linode":            "iaas",
        "rackspace":         "iaas",
        "vultr":             "iaas",
        "cloud storage":     "iaas",
    }

     # --- 0. Blank input ---
    if not low:
        frame["needs_more_info"] = True
        frame["reason"] = "Needs more information: Blank or missing answer text."
        return frame

    # --- 1. Immediate compliance if 'attached' ---
    if "attached" in low:
        frame["compliant"] = True
        frame["reason"] = "Compliant: Applicant states information is attached separately."
        return frame

    # --- 2. regex scan over text ---
    matched = []
    low_nospaces = re.sub(r'\s+', '', low)
    for svc in KNOWN_CLOUD:
        svc_nospaces = svc.replace(" ", "")
        if svc in low or svc_nospaces in low_nospaces:
            matched.append(svc)

    # --- 3. spaCy fallback: add ORG/PRODUCT entities with cloud-ish keywords ---
    cloud_fallback_keywords = (
        "cloud", "drive", "storage", "online", "365", "gcp", "aws", "azure", "exchange",
        "service", "apps", "saas", "paas", "iaas", ".com"
    )
    for ent in doc.ents:
        t = ent.text.lower().strip()
        if ent.label_ in {"ORG", "PRODUCT"} and t not in [m.lower() for m in matched]:
            if any(kw in t for kw in cloud_fallback_keywords):
                matched.append(ent.text.strip())

    # --- Deduplicate, preserve first occurrence ---
    seen, cloud_services = set(), []
    for s in matched:
        key = s.lower()
        if key not in seen:
            cloud_services.append(s)
            seen.add(key)
    frame["cloud_services"] = cloud_services

    # --- 4. Explicit labels in answer ---
    if "saas" in low: frame["service_types"]["saas"] += frame["cloud_services"]
    if "paas" in low: frame["service_types"]["paas"] += frame["cloud_services"]
    if "iaas" in low: frame["service_types"]["iaas"] += frame["cloud_services"]

    # --- 5. Dictionary mapping fallback ---
    for svc in frame["cloud_services"]:
        svc_type = KNOWN_CLOUD.get(svc.lower())
        if svc_type:
            frame["service_types"][svc_type].append(svc)

    # Deduplicate service types
    for k in frame["service_types"]:
        frame["service_types"][k] = sorted(set(frame["service_types"][k]))

    # --- 6. Compliance logic ---
    if frame["cloud_services"]:
        frame["compliant"] = True
    else:
        if re.search(r"\b(none?|n/a|no cloud|not applicable)\b", low):
            frame["non_compliant_missing"] = True
        else:
            frame["needs_more_info"] = True
        frame["missing_cloud_flag"] = True

    # --- 7. Reason assignment ---
    if frame["compliant"]:
        svc_list = ", ".join(frame["cloud_services"])
        type_summary = []
        for k in ["saas", "paas", "iaas"]:
            if frame["service_types"][k]:
                type_summary.append(f"{k.upper()}: {', '.join(frame['service_types'][k])}")
        if type_summary:
            frame["reason"] = f"Compliant: Cloud services listed – {svc_list}. Types: {'; '.join(type_summary)}."
        else:
            frame["reason"] = f"Compliant: Cloud services listed – {svc_list}."
    elif frame["non_compliant_missing"]:
        frame["reason"] = "Non-compliant: Applicant states no cloud services in use, which contradicts expected usage."
    elif frame["needs_more_info"]:
        frame["reason"] = "Needs more information: No clear cloud services identified; response is vague or incomplete."
    else:
        frame["reason"] = "Needs more information: Cloud service listing unclear or improperly formatted."

    return frame








# --------------------------------------------------------------------------- #
# A4.12  ―
# --------------------------------------------------------------------------- #
def rule_a4_12(text):
    doc = nlp(text)
    lowered = text.lower()

    frame = {
        "mentions_os": [],
        "firewall_not_available_claim": False,
        "unsupported_os_claim": False,
        "contradiction_detected": False,
        "compliant": False,
        "non_compliant": False,
        "needs_more_info": False,
        "reason": ""
    }

    # Known OS and related product names (expand as needed)
    known_os = [
        "windows 10", "windows 11", "windows", "macos", "os x", "ubuntu", "debian", "linux", "redhat",
        "centos", "arch", "fedora", "kali", "parrot", "embedded linux", "unix", "custom os", "bespoke",
        "custom build", "android", "ios", "raspbian", "chromeos", "chromebook"
    ]
    known_os = [k.lower() for k in known_os]

    # Extract OS/product mentions using spaCy
    for ent in doc.ents:
        if ent.label_ in ("PRODUCT", "ORG", "NORP") and ent.text.lower() not in frame["mentions_os"]:
            # Accept spaCy OS/product-like entities
            frame["mentions_os"].append(ent.text.lower())
    # Also match any from the known_os list (string match fallback)
    for os_name in known_os:
        if os_name in lowered and os_name not in frame["mentions_os"]:
            frame["mentions_os"].append(os_name)

    # Detect claim that software firewall is unavailable/missing
    if re.search(r"(no (built[- ]?in |default )?software firewall|not (have|include|contain) software firewall|firewall (not|never) available|cannot.*firewall)", lowered):
        frame["firewall_not_available_claim"] = True

    # Detect claim of unsupported or custom/uncommon OS
    if re.search(r"(embedded linux|bespoke|custom os|bare metal|minimal linux|no gui|headless|custom build)", lowered):
        frame["unsupported_os_claim"] = True

    # Contradiction logic: claims common OS lacks firewall (which is false)
    contradiction_oses = {"windows", "windows 10", "windows 11", "macos", "os x", "ubuntu", "debian", "fedora", "arch", "centos", "redhat"}
    for os in frame["mentions_os"]:
        if os in contradiction_oses and frame["firewall_not_available_claim"]:
            frame["contradiction_detected"] = True
            frame["non_compliant"] = True

    # Needs more info if claim is made but OS not named or is too vague
    if frame["firewall_not_available_claim"] and not frame["mentions_os"]:
        frame["needs_more_info"] = True

    # If claim is made, OS is *not* a real exception, but no contradiction: non-compliance
    if frame["firewall_not_available_claim"] and not frame["unsupported_os_claim"] and not frame["contradiction_detected"]:
        frame["non_compliant"] = True

    # If they list only custom OS (real exceptions): compliant
    if frame["firewall_not_available_claim"] and frame["unsupported_os_claim"]:
        frame["compliant"] = True

    # If applicant simply lists only OSes where a firewall is always available, and doesn't claim otherwise: compliant
    if (not frame["firewall_not_available_claim"]
        and all(os in contradiction_oses for os in frame["mentions_os"])
        and frame["mentions_os"]):
        frame["compliant"] = True

    # If nothing is mentioned, needs more info
    if not frame["mentions_os"] and not frame["firewall_not_available_claim"]:
        frame["needs_more_info"] = True

    # --- Reason assignment ---
    if frame["compliant"]:
        if frame["unsupported_os_claim"]:
            frame["reason"] = "Compliant: Software firewall not available on unsupported or custom OS."
        else:
            frame["reason"] = f"Compliant: Listed OS(es) ({', '.join(frame['mentions_os'])}) are known to include built-in firewalls and no claim was made otherwise."
    elif frame["non_compliant"]:
        if frame["contradiction_detected"]:
            frame["reason"] = f"Non-compliant: Claimed firewall not available on OS ({', '.join(frame['mentions_os'])}) known to include one."
        else:
            frame["reason"] = "Non-compliant: Claimed lack of firewall on standard OS without justification."
    elif frame["needs_more_info"]:
        if frame["firewall_not_available_claim"] and not frame["mentions_os"]:
            frame["reason"] = "Needs more information: Applicant claimed firewall is unavailable but did not specify which OS."
        else:
            frame["reason"] = "Needs more information: No OS or firewall-related details provided."
    else:
        frame["reason"] = "Needs more information: Incomplete or unclear firewall availability explanation."

    return frame




# --------------------------------------------------------------------------- #
# A6.2.1  ―
# --------------------------------------------------------------------------- #

def rule_a6_2_1(text: str) -> dict:
    """
    Extracts browsers and versions, being lenient: any number after a browser is treated as version.
    - If 'attached' is present: compliant.
    - Legacy browsers are non-compliant.
    - Outdated versions as per guidance are non-compliant.
    - Otherwise, needs_more_info if no browser+version.
    """
    doc = nlp(text)
    lowered = text.lower()
    frame = {
        "browsers_listed":      [],
        "versions_provided":    False,
        "unsupported_browser":  False,
        "outdated_version":     False,
        "compliant":            False,
        "needs_more_info":      False,
        "non_compliant":        False,
        "reason":               ""
    }

    if "attached" in lowered:
        frame["compliant"] = True
        return frame

    browser_names = [
    "chrome", "edge", "firefox", "safari", "opera", "chromium", "brave",
    "samsung internet", "vivaldi", "tor", "yandex", "uc browser",
    "maxthon", "puffin", "palemoon", "waterfox", "internet explorer",
    "avast secure browser", "duckduckgo browser"
    ]
    browser_rx = r"|".join([
    r"(?:samsung\s+internet)", "chrome", "edge", "firefox", "safari", "opera",
    "chromium", "brave", "vivaldi", "tor", "yandex", "uc\s+browser",
    "maxthon", "puffin", "palemoon", "waterfox", "internet\s+explorer",
    "avast\s+secure\s+browser", "duckduckgo\s+browser"
     ])

    version_pat = re.compile(
        rf"({browser_rx})[^\w\d]{{0,10}}v?(ersion)?[^\w\d]{{0,5}}([0-9]+(?:\.[0-9]+){{0,3}})",
        re.I
    )
    loose_pat = re.compile(
        rf"({browser_rx})[^\w\d]{{0,10}}([0-9]+(?:\.[0-9]+){{0,3}})",
        re.I
    )

    min_supported_major = {
        "chrome":   110,
        "edge":     110,
        "firefox":  110,
        "safari":   15,
        "opera":    95,
        "chromium": 110,
        "brave":    110,
        "samsung internet": 22
    }
    legacy_list = [
        "internet explorer", "ie6", "ie7", "ie8", "ie9", "ie10", "ie11",
        "netscape", "uc browser", "konqueror", "maxthon", "waterfox classic"
    ]

    found_versions = []
    found_browsers = set()
    outdated = False

    for m in version_pat.finditer(lowered):
        browser = m.group(1).strip()
        version = m.group(3)
        found_browsers.add(browser)
        found_versions.append((browser, version))
        try:
            major = int(version.split(".")[0])
            if major < min_supported_major.get(browser, 0):
                outdated = True
        except Exception:
            pass

    for m in loose_pat.finditer(lowered):
        browser = m.group(1).strip()
        version = m.group(2)
        if (browser, version) not in found_versions:
            found_browsers.add(browser)
            found_versions.append((browser, version))
            try:
                major = int(version.split(".")[0])
                if major < min_supported_major.get(browser, 0):
                    outdated = True
            except Exception:
                pass

    for browser in browser_names:
        if re.search(browser, lowered) and browser not in found_browsers:
            found_browsers.add(browser)

    for ent in doc.ents:
        if ent.label_ == "PRODUCT":
            prod = ent.text.lower()
            if prod in browser_names and prod not in found_browsers:
                found_browsers.add(prod)

    if any(legacy in lowered for legacy in legacy_list):
        frame["unsupported_browser"] = True

    frame["browsers_listed"] = sorted(found_browsers)
    frame["versions_provided"] = bool(found_versions)
    frame["outdated_version"] = outdated

    # --- HERE IS THE CRUCIAL FIX ---
    # If any version pattern appears anywhere and any browser is present, treat as version provided
    if not frame["versions_provided"] and frame["browsers_listed"]:
        if re.search(r"\b\d+(\.\d+){1,3}\b", lowered):
            frame["versions_provided"] = True

    if frame["unsupported_browser"] or frame["outdated_version"]:
        frame["non_compliant"] = True
    elif frame["browsers_listed"] and frame["versions_provided"]:
        frame["compliant"] = True
    else:
        frame["needs_more_info"] = True

    # --- Reason assignment ---
    if frame["compliant"]:
        frame["reason"] = f"Compliant: Supported browser(s) listed ({', '.join(frame['browsers_listed'])}) with valid version(s)."
    elif frame["non_compliant"]:
        if frame["unsupported_browser"]:
            frame["reason"] = "Non-compliant: Legacy or unsupported browser mentioned (e.g. Internet Explorer)."
        elif frame["outdated_version"]:
            frame["reason"] = "Non-compliant: Browser version is below the minimum supported level."
        else:
            frame["reason"] = "Non-compliant: Unsupported configuration detected."
    elif frame["needs_more_info"]:
        if not frame["browsers_listed"]:
            frame["reason"] = "Needs more information: No identifiable browser found in the response."
        elif not frame["versions_provided"]:
            frame["reason"] = "Needs more information: Browser(s) listed without any version information."
        else:
            frame["reason"] = "Needs more information: Partial browser/version information; unclear compliance."

    return frame







# --------------------------------------------------------------------------- #
# A6.2.2  ―
# --------------------------------------------------------------------------- #
from typing import List, Dict
import re

def rule_a6_2_2(text: str) -> dict:
    """
    A6.2.2 – List your malware‑protection software (version required)
    Robust: Accepts any number as a version if a tool is listed.
    - If 'attached' present: compliant.
    - Unsupported/legacy tools: non-compliant.
    - Outdated versions: non-compliant.
    - Otherwise, needs_more_info if no tool+version.
    """
    doc = nlp(text)
    lowered = text.lower()

    frame = {
        "malware_tools":     [],
        "unsupported_tools": [],
        "outdated_version":  False,
        "versions_provided": False,
        "unsupported_flag":  False,
        "compliant":         False,
        "needs_more_info":   False,
        "non_compliant":     False,
        "reason":            ""
    }

    if "attached" in lowered:
        frame["compliant"] = True
        return frame

    av_names = [
    # Microsoft
    "windows defender", "microsoft defender", "defender for endpoint", "ms defender", "msrt",
    # Sophos, CrowdStrike, SentinelOne
    "sophos", "crowdstrike", "sentinelone", "sentinel one",
    # Bitdefender, ESET, Kaspersky, Trend Micro
    "bitdefender", "eset", "kaspersky", "trend micro", "trendmicro",
    # McAfee, Trellix (rebranded McAfee)
    "mcafee", "trellix",
    # Webroot, Huntress, Rapid7, Cortex XDR
    "webroot", "huntress", "rapid7", "cortex xdr", "palo alto cortex", "palo alto networks cortex",
    # Malwarebytes, ClamAV, XProtect (Mac)
    "malwarebytes", "clamav", "xprotect",
    # Norton, Symantec, Avast, AVG (classic/legacy)
    "norton", "symantec", "avast", "avg", "avira", "f-secure", "bullguard",
    # Dr.Web, G Data, Comodo, Panda, ZoneAlarm, Qihoo 360, Webroot, Adaware
    "dr.web", "drweb", "g data", "comodo", "panda", "zonealarm", "qihoo 360", "adaware",
    # Cylance, Carbon Black, Sophos Intercept X, Vipre, Fortinet/FortiClient, FireEye
    "cylance", "carbon black", "vmware carbon black", "intercept x", "vipre", "fortinet", "forticlient", "fireeye",
    # Mac-specific
    "xprotect", "santa", "jamf protect", "macafee",   # typo included
    # Miscellaneous, new/other (for future-proofing)
    "secureanywhere", "cybereason", "secureworks", "cybereason", "mcshield", "trend officescan",
    "malwarebytes endpoint protection", "bitdefender gravityzone", "sentinelone ranger"
]

    av_rx = {
        name: re.compile(rf"{re.escape(name)}[^\w\d]{{0,6}}v?(ersion)?[^\w\d]{{0,4}}?([\d\.]+)?", re.I)
        for name in av_names
    }
    min_major = {
        "windows defender": 0, "microsoft defender": 0, "sentinelone": 22,
        "crowdstrike": 6, "sophos": 10, "bitdefender": 7, "eset": 9,
        "kaspersky": 21, "trend micro": 12,
    }
    legacy_rx = {
        "avg": r"\bavg\b",
        "avast": r"\bavast\b",
        "windows live onecare": r"windows live onecare",
        "ms security essentials": r"microsoft security essentials",
        "norton (old)": r"norton(?: antivirus| 360)?\s*(v?\d{1,2})?",
        "panda free": r"panda (?:free|security)",
        "malwarebytes free": r"malwarebytes(?!.*premium)",
    }

    found_tools = set()
    found_versions = set()
    outdated = False

    # 1. Regex match for known tools + attached version
    for name, rx in av_rx.items():
        for m in rx.finditer(lowered):
            found_tools.add(name)
            ver = m.group(2)
            if ver and re.search(r"\d", ver):
                found_versions.add(ver)
                try:
                    major = int(ver.split(".")[0])
                    if major < min_major.get(name, 0):
                        outdated = True
                except Exception:
                    pass

    # 2. Legacy/unsupported check
    for name, rx in legacy_rx.items():
        if re.search(rx, lowered):
            frame["unsupported_tools"].append(name)
            frame["unsupported_flag"] = True

    # 3. spaCy fallback for PRODUCT/ORG names
    for ent in doc.ents:
        if ent.label_ in {"PRODUCT", "ORG"}:
            token = ent.text.lower()
            for name in av_names:
                if name in token and name not in found_tools:
                    found_tools.add(name)

    # 4. Version-like numbers anywhere in the text (catch all)
    all_versions = set(re.findall(r"\b\d+(\.\d+){1,3}\b", lowered))
    # Accept any number with at least one dot and not part of a date (YYYY.MM.DD etc)
    generic_versions = set(re.findall(r"\b\d+\.\d+(?:\.\d+){0,2}\b", lowered))
    if found_tools and (found_versions or generic_versions):
        frame["versions_provided"] = True

    frame["malware_tools"] = sorted(found_tools)
    frame["unsupported_tools"] = sorted(set(frame["unsupported_tools"]))
    frame["outdated_version"] = outdated

    # 5. Label logic
    if frame["unsupported_flag"] or frame["outdated_version"]:
        frame["non_compliant"] = True
    elif frame["malware_tools"] and frame["versions_provided"]:
        frame["compliant"] = True
    else:
        frame["needs_more_info"] = True

    # --- Reason assignment ---
    if frame["compliant"]:
        frame["reason"] = f"Compliant: Malware protection tool(s) listed ({', '.join(frame['malware_tools'])}) with version(s)."
    elif frame["non_compliant"]:
        if frame["unsupported_flag"]:
            frame["reason"] = f"Non-compliant: Unsupported or legacy tool(s) detected ({', '.join(frame['unsupported_tools'])})."
        elif frame["outdated_version"]:
            frame["reason"] = "Non-compliant: Malware protection version is below minimum supported level."
        else:
            frame["reason"] = "Non-compliant: Tool or version provided is not acceptable."
    elif frame["needs_more_info"]:
        if not frame["malware_tools"]:
            frame["reason"] = "Needs more information: No malware protection tool detected."
        elif not frame["versions_provided"]:
            frame["reason"] = "Needs more information: Tool listed without a version number."
        else:
            frame["reason"] = "Needs more information: Incomplete version or tool information."

    return frame











# ------------------------------------------------------------------ #
#  A6.2.3 – “List your e‑mail applications”
# ------------------------------------------------------------------ #

from typing import List, Dict
import re

def rule_a6_2_3(text: str) -> Dict[str, object]:
    """
    A6.2.3 – List your email applications (version required)
    - Any 'attached', 'see attached', 'see appendix', etc: compliant.
    - Legacy/unsupported clients: non-compliant.
    - Any number with a dot, anywhere with an app: counts as version provided.
    - Webmail/browser access with app: counts as version provided.
    - Otherwise, needs_more_info if no app+version.
    """
    doc = nlp(text)
    lowered = text.lower()

    frame = {
        "email_apps":         [],
        "unsupported_apps":   [],
        "versions_provided":  False,
        "unsupported_flag":   False,
        "compliant":          False,
        "non_compliant":      False,
        "needs_more_info":    False,
        "reason":             ""
    }

    # --- 1. Accept "see attached", "see appendix", etc as compliant
    attach_phrases = [
        "attached", "see attached", "see appendix", "see schedule", "see document"
    ]
    if any(phrase in lowered for phrase in attach_phrases):
        frame["compliant"] = True
        return frame

    # --- 2. Known/accepted app variants and aliases

    app_names = [
    # Apple/macOS/iOS
    "mac mail", "apple mail", "mail", "mail app", "iphone mail", "ipad mail", "ipados mail",
    # Microsoft
    "outlook", "ms outlook", "microsoft outlook", "exchange", "ms exchange",
    "office 365", "microsoft 365", "ms 365", "o365", "m365",
    "windows mail", "windows live mail", "outlook express",
    # Google
    "gmail", "google mail", "google workspace", "g suite",
    # Linux/Open source
    "thunderbird", "evolution", "kmail", "geary", "claws mail", "alpine",
    # Third-party multiplatform and niche
    "mailbird", "em client", "spark", "bluemail", "protonmail", "zoho mail",
    "aqua mail", "nine mail", "yahoo mail", "mail.com", "fastmail", "mail.ru",
    "postbox", "foxmail", "zimbra", "horde", "roundcube", "kolab", "sogo",
    "supra mail", "superhuman",
    # Legacy and enterprise
    "eudora", "pegasus mail", "lotus notes",
    # Android specific
    "samsung mail", "android mail", "blackberry hub",
    # Miscellaneous/web-based (catch-all)
    "webmail", "browser-based mail", "browser mail", "web based mail"
]


    # --- 3. Regex to find tool+version pairs (robust spacing/wording)
    app_rx = {
        name: re.compile(rf"{re.escape(name)}[^\w\d]{{0,8}}v?(ersion)?[^\w\d]{{0,6}}?([\d\.]+)?", re.I)
        for name in app_names
    }

    # --- 4. Legacy/unsupported clients
    legacy_rx = {
        "outlook 2010":        r"outlook\s*2010",
        "outlook 2013":        r"outlook\s*2013",
        "outlook express":     r"outlook\s*express",
        "windows live mail":   r"windows\s*live\s*mail",
        "lotus notes":         r"lotus\s*notes",
        "eudora":              r"eudora",
    }

    # --- 5. Webmail/browser phrases
    webmail_phrases = [
        "webmail", "web-based", "web based", "browser", "accessed through browser", "accessed via web", "web email", "webemail"
    ]

    found_apps = set()
    found_versions = set()

    # --- 6. Regex match for known apps + attached version
    for name, rx in app_rx.items():
        for m in rx.finditer(lowered):
            found_apps.add(name)
            ver = m.group(2)
            if ver and re.search(r"\d", ver):
                found_versions.add(ver)

    # --- 7. Legacy/unsupported check
    for label, rx in legacy_rx.items():
        if re.search(rx, lowered):
            frame["unsupported_apps"].append(label)
            frame["unsupported_flag"] = True

    # --- 8. spaCy fallback for PRODUCT/ORG names
    for ent in doc.ents:
        if ent.label_ in {"PRODUCT", "ORG"}:
            token = ent.text.lower()
            for name in app_names:
                if name in token and name not in found_apps:
                    found_apps.add(name)

    # --- 9. Alias match in text (e.g., "o365", "m365")
    for alias in ["ms outlook", "ms exchange", "ms 365", "o365", "m365", "google mail"]:
        if alias in lowered and alias not in found_apps:
            found_apps.add(alias)

    # --- 10. Webmail/browser logic: if app and webmail/browser phrase, count as version provided
    if found_apps and any(phrase in lowered for phrase in webmail_phrases):
        frame["versions_provided"] = True

    # --- 11. Generic version pattern: any number with at least one dot, anywhere, if app present
    if found_apps and (found_versions or re.search(r"\b\d+\.\d+(?:\.\d+){0,2}\b", lowered)):
        frame["versions_provided"] = True

    frame["email_apps"] = sorted(found_apps)
    frame["unsupported_apps"] = sorted(set(frame["unsupported_apps"]))

       # --- 11b. If "version" (with misspellings) is followed by number, count as version provided
    if found_apps:
        # Accept "version", "verison", "versoin", "vers", etc., followed by optional ":" or space, then number
        version_word_rx = r"\bver(?:sion|sion|ison|soin|s|rsion|rison)?\b[\s:]*([0-9]+(?:\.[0-9]+){0,3})"
        if re.search(version_word_rx, lowered):
            frame["versions_provided"] = True

    # --- 12. Label logic
    if frame["unsupported_flag"]:
        frame["non_compliant"] = True
    elif frame["email_apps"] and frame["versions_provided"]:
        frame["compliant"] = True
    else:
        frame["needs_more_info"] = True

    # --- Reason assignment ---
    if frame["compliant"]:
        frame["reason"] = f"Compliant: Email app(s) listed ({', '.join(frame['email_apps'])}) with version(s) or browser-based access."
    elif frame["non_compliant"]:
        frame["reason"] = f"Non-compliant: Unsupported or legacy email client(s) detected ({', '.join(frame['unsupported_apps'])})."
    elif frame["needs_more_info"]:
        if not frame["email_apps"]:
            frame["reason"] = "Needs more information: No email applications detected."
        elif not frame["versions_provided"]:
            frame["reason"] = "Needs more information: Email app(s) listed but version information is missing."
        else:
            frame["reason"] = "Needs more information: Incomplete information on email tools and versions."

    return frame










# ------------------------------------------------------------------ #
#  A6.2.4 – “List Office applications that create organisational data”
# ------------------------------------------------------------------ #
from typing import List, Dict
import re

def rule_a6_2_4(text: str) -> Dict[str, object]:
    """
    A6.2.4 – List your office/document software (version required)
    - Accepts 'attached', 'see appendix', etc as compliant.
    - Legacy/EOL suites: non-compliant.
    - If 'version' (misspelled ok) is followed by a number (with or without dot): version provided.
    - Otherwise, only numbers with at least one dot (e.g. X.Y, X.Y.Z) count as version.
    - Browser/web/online logic: version provided if app and phrase.
    - Otherwise, needs_more_info if no app+version.
    """
    doc = nlp(text)
    lowered = text.lower()

    frame = {
        "office_apps":        [],
        "unsupported_apps":   [],
        "versions_provided":  False,
        "unsupported_flag":   False,
        "compliant":          False,
        "non_compliant":      False,
        "needs_more_info":    False,
        "reason":             ""
    }

    # 1. Accept "see attached", "see appendix", etc as compliant
    attach_phrases = [
        "attached", "see attached", "see appendix", "see schedule", "see document"
    ]
    if any(phrase in lowered for phrase in attach_phrases):
        frame["compliant"] = True
        return frame

    # 2. Known/accepted suites + aliases
    app_names = [
        "microsoft 365", "ms 365", "office 365", "microsoft office", "ms office", "o365", "m365",
        "google workspace", "google docs", "google drive", "gsuite", "g suite",
        "libreoffice", "libre office", "onlyoffice", "only office",
        "office 2016", "office 2019", "office 2021", "office 2024",
        "affinity publisher", "adobe creative cloud", "adobe cc", "adobe suite", "adobe creative suite",
        "netdocuments", "ndoffice", "wps office", "wps", "openoffice", "open office"
    ]
    app_rx = {
        name: re.compile(rf"{re.escape(name)}[^\w\d]{{0,8}}v?(ersion)?[^\w\d]{{0,6}}?([\d\.]+)?", re.I)
        for name in app_names
    }

    # 3. Legacy/EOL suites
    legacy_rx = {
        "office 2010":        r"office\s*2010",
        "office 2013":        r"office\s*2013",
        "openoffice":         r"open[\s\-]?office",
        "lotus notes":        r"lotus\s+notes",
        "wordperfect":        r"wordperfect",
    }

    # 4. Web/online/browser access phrases
    web_phrases = [
        "web-based", "web based", "browser", "browser-based", "online", "cloud", "online version"
    ]

    found_apps = set()
    found_versions = set()
    found_version_word = False

    # 5. Regex match for known apps + attached version
    for name, rx in app_rx.items():
        for m in rx.finditer(lowered):
            found_apps.add(name)
            ver = m.group(2)
            if ver and re.search(r"\d", ver):
                found_versions.add(ver)

    # 6. Legacy/EOL check
    for label, rx in legacy_rx.items():
        if re.search(rx, lowered):
            frame["unsupported_apps"].append(label)
            frame["unsupported_flag"] = True

    # 7. spaCy PRODUCT fallback
    SUITE_HINT = re.compile(r"(office|suite|docs|cloud|workspace|wps|libre)", re.I)
    for ent in doc.ents:
        if ent.label_ == "PRODUCT" and SUITE_HINT.search(ent.text):
            t = ent.text.strip()
            if t.lower() not in [a.lower() for a in found_apps]:
                found_apps.add(t)

    # 8. Alias matching (e.g., "o365", "m365", "gsuite")
    for alias in ["ms 365", "ms office", "o365", "m365", "gsuite", "libre office", "open office"]:
        if alias in lowered and alias not in found_apps:
            found_apps.add(alias)

    # 9. Web/online/browser logic: if app and web phrase, version provided
    if found_apps and any(phrase in lowered for phrase in web_phrases):
        frame["versions_provided"] = True

    # 10. "version" (misspelled ok) followed by number (any digits, with or without dot)
    if found_apps:
        # Accept "version", "verison", "versoin", etc., followed by number (with or without dot)
        version_word_rx = r"\bver(?:sion|sion|ison|soin|s|rsion|rison)?\b[\s:]*([0-9]+(?:\.[0-9]+){0,3}|[0-9]+)"
        m = re.search(version_word_rx, lowered)
        if m:
            frame["versions_provided"] = True
            found_version_word = True

    # 11. Generic version pattern: any number with at least one dot, if app present and no 'version' word found
    if found_apps and not frame["versions_provided"]:
        if re.search(r"\b\d+\.\d+(?:\.\d+){0,2}\b", lowered):
            frame["versions_provided"] = True

    frame["office_apps"] = sorted(found_apps)
    frame["unsupported_apps"] = sorted(set(frame["unsupported_apps"]))

    # 12. Label logic
    if frame["unsupported_flag"]:
        frame["non_compliant"] = True
    elif frame["office_apps"] and frame["versions_provided"]:
        frame["compliant"] = True
    else:
        frame["needs_more_info"] = True

    # --- Reason assignment ---
    if frame["compliant"]:
        frame["reason"] = f"Compliant: Office/document software listed ({', '.join(frame['office_apps'])}) with version(s) or browser-based access."
    elif frame["non_compliant"]:
        frame["reason"] = f"Non-compliant: Unsupported or legacy software detected ({', '.join(frame['unsupported_apps'])})."
    elif frame["needs_more_info"]:
        if not frame["office_apps"]:
            frame["reason"] = "Needs more information: No office or document editing software detected."
        elif not frame["versions_provided"]:
            frame["reason"] = "Needs more information: Software listed but version information missing."
        else:
            frame["reason"] = "Needs more information: Incomplete details about document software and versioning."


    return frame




#  Register rule dispatch map
question_rules = {
"A2.2": rule_a2_2,
"A2.10": rule_a2_10,
"A2.3": rule_a2_3,
"A2.4": rule_a2_4,
"A2.4.1": rule_a2_4_1,
"A2.5": rule_a2_5,
"A2.6": rule_a2_6,
"A2.7": rule_a2_7,
"A2.7.1": rule_a2_7_1,
"A2.8": rule_a2_8,
"A2.9": rule_a2_9,
"A4.12": rule_a4_12,
"A6.2.1": rule_a6_2_1,
"A6.2.2": rule_a6_2_2,
"A6.2.3": rule_a6_2_3,
"A6.2.4": rule_a6_2_4

}



# --- semantic extraction function ---
def extract_semantic_frame(question_id, answer_text):
    rule_fn = question_rules.get(question_id)
    if rule_fn is None:
        return None
    return rule_fn(answer_text)

# --- Extract status + reason from semantic frame ---
def get_compliance_label_and_reason(frame: dict, blank_text: str = None) -> (str, str):
    # Optional: Pass the answer text as blank_text for blank check
    if blank_text is not None and not blank_text.strip():
        return "Fail", "Answer is blank."
    if not frame or not isinstance(frame, dict):
        return "Unknown", ""
    if frame.get("auto_fail"):
        return "Fail", frame.get("reason", "")
    if frame.get("compliant"):
        return "Compliant", frame.get("reason", "")
    if frame.get("needs_more_info"):
        return "More-information", frame.get("reason", "")
    if frame.get("non_compliant"):
        return "Non-compliant", frame.get("reason", "")
    return "Unknown", frame.get("reason", "")



# ---------------------------------------------------------------
# Public helper expected by the evaluation script
# ---------------------------------------------------------------
def apply_rule(question_id: str, answer_text: str) -> str:
    """
    Run the semantic rule for `question_id` on `answer_text`
    and return ONLY the top-level compliance label.

    Possible return values:
        'Compliant', 'Non-compliant', 'Fail', 'More-information', 'Unknown'
    """
    frame = extract_semantic_frame(question_id, answer_text)
    label, _ = get_compliance_label_and_reason(frame, answer_text)
    return label



def apply_rule_with_reason(question_id: str, answer_text: str) -> tuple[str, str]:
    frame = extract_semantic_frame(question_id, answer_text)
    return get_compliance_label_and_reason(frame, answer_text)


Overwriting semantic_rules.py


In [ ]:
import importlib, semantic_rules as sr
importlib.reload(sr)


<module 'semantic_rules' from '/content/semantic_rules.py'>

In [ ]:
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from semantic_rules import apply_rule, question_rules  # or `import sr` if aliased as sr

# === 1. Load manually annotated data ===
CSV_PATH = "/content/drive/MyDrive/project/CB/manual_annotated_questions.csv"
df = pd.read_csv(CSV_PATH, dtype=str).fillna("")

# === 2. Filter to questions that have semantic rules ===
RULE_IDS = set(question_rules.keys())
df_rule = df[df["question_id"].isin(RULE_IDS)].copy()

# === 3. Apply semantic rule function to get predicted compliance ===
df_rule["predicted_compliance"] = df_rule.apply(
    lambda row: apply_rule(row["question_id"], row["answer_text"]),
    axis=1
)

# === 4. Normalize manual + predicted labels (strip spaces) ===
def normalize_label(label):
    return label.strip().lower().capitalize() if isinstance(label, str) else label

df_rule["compliance"] = df_rule["compliance"].apply(normalize_label)
df_rule["predicted_compliance"] = df_rule["predicted_compliance"].apply(normalize_label)

# === 5. Apply blank / “not applicable” override → Fail ===
for i, row in df_rule.iterrows():
    ans = str(row["answer_text"]).strip().lower()
    if ans in {"", "n/a", "na", "none", "not applicable", "."}:
        df_rule.at[i, "predicted_compliance"] = "Fail"

# === 6. Filter out rows with empty or unknown labels ===
df_eval = df_rule[
    (df_rule["compliance"] != "") &
    (df_rule["predicted_compliance"] != "") &
    (df_rule["predicted_compliance"] != "Unknown")
].copy()

# === 7. Evaluate ===
print("=== Classification Report ===")
print(classification_report(
    df_eval["compliance"],
    df_eval["predicted_compliance"],
    labels=["Compliant", "Non-compliant", "Fail", "More-information"],
    zero_division=0
))

print("\n=== Confusion Matrix ===")
print(confusion_matrix(
    df_eval["compliance"],
    df_eval["predicted_compliance"],
    labels=["Compliant", "Non-compliant", "Fail", "More-information"]
))

# === 8. Optional: Show mismatches ===
mismatches = df_eval[df_eval["compliance"] != df_eval["predicted_compliance"]]
print(f"\n❌ Mismatches: {len(mismatches)}")
try:
    display(mismatches[["file", "question_id", "compliance", "predicted_compliance", "answer_text"]].head(10))
except NameError:
    print(mismatches[["file", "question_id", "compliance", "predicted_compliance", "answer_text"]]
          .head(10).to_string(index=False))


=== Classification Report ===
                  precision    recall  f1-score   support

       Compliant       1.00      1.00      1.00       657
   Non-compliant       1.00      1.00      1.00         8
            Fail       1.00      1.00      1.00       104
More-information       1.00      1.00      1.00       148

        accuracy                           1.00       917
       macro avg       1.00      1.00      1.00       917
    weighted avg       1.00      1.00      1.00       917


=== Confusion Matrix ===
[[657   0   0   0]
 [  0   8   0   0]
 [  0   0 104   0]
 [  0   0   0 148]]

❌ Mismatches: 0


Empty DataFrame
Columns: [file, question_id, compliance, predicted_compliance, answer_text]
Index: []

The semantic frame component was tested on 917 items covering list-based questions. Accuracy reached 100% across all classes (Compliant, Non-Compliant, Fail, More-Information), with zero mismatches against manual annotations (Figure 3). To ensure full slot coverage, all tools, roles, and devices observed in the development corpus were added to the EntityRuler patterns. When NLP models (spaCy, GeoTxt) did not resolve locations, versions, unsupported devices, or Windows variants, these were added manually to the dictionary, guaranteeing corpus-wide recall.

### Evaluation of the reasons

In [ ]:
import pandas as pd
import re
from semantic_rules import apply_rule_with_reason, question_rules

# === 1) Load dataset ===
csv_path = "/content/drive/MyDrive/project/CB/manual_annotated_questions.csv"
df = pd.read_csv(csv_path, dtype=str).fillna("")

# === 2) Filter only semantic-frame questions ===
RULE_IDS = set(question_rules.keys())
df_sem = df[df["question_id"].isin(RULE_IDS)].copy()

# === 3) Predict (label, reason) ===
def get_label_and_reason(row):
    label, reason = apply_rule_with_reason(row["question_id"], str(row["answer_text"]).strip())
    return pd.Series([label, reason])

df_sem[["predicted_compliance", "reason"]] = df_sem.apply(get_label_and_reason, axis=1)

# === 4) Normalise labels ===
def norm_label(s):
    if not isinstance(s, str): return ""
    t = s.strip().lower()
    if t in {"non-compliant","non compliant","noncompliant"}: return "Non-compliant"
    if t == "compliant": return "Compliant"
    if t in {"fail","failed"}: return "Fail"
    if t in {"more-information","more information","moreinformation","more info"}: return "More-information"
    if t == "unknown": return "Unknown"
    return t.capitalize()

df_sem["predicted_compliance"] = df_sem["predicted_compliance"].apply(norm_label)

# ---------------------------------------------------------------------
# === 5) Evaluation Metrics ===
# ---------------------------------------------------------------------

# 5a. Coverage
total = len(df_sem)
has_reason = df_sem["reason"].astype(str).str.strip().ne("") & df_sem["reason"].notna()
num_with_reason = int(has_reason.sum())
print(f"\nReason coverage: {num_with_reason}/{total} ({100.0*num_with_reason/total:.2f}%)")

# Optional coverage by label
by_label = (
    df_sem.assign(has_reason=has_reason.astype(int))
          .groupby("predicted_compliance")["has_reason"]
          .agg(total="count", with_reason="sum")
)
by_label["pct_with_reason"] = 100.0 * by_label["with_reason"] / by_label["total"].clip(lower=1)
print("\nCoverage by predicted label:")
print(by_label.sort_index().to_string())

# 5b. Specificity: check if reason references evidence (numbers, OS, services, etc.)
def has_evidence(reason):
    if not isinstance(reason, str): return False
    return bool(re.search(r"\b\d+\b", reason)) or \
           bool(re.search(r"(windows|macos|linux|ios|android|azure|aws|gcp|onedrive|365)", reason.lower()))

df_sem["has_evidence"] = df_sem["reason"].apply(has_evidence)
spec_stats = df_sem.groupby("predicted_compliance")["has_evidence"].mean()*100
print("\nSpecificity (% reasons with extracted evidence):")
print(spec_stats.round(1).to_string())

# 5d. Marking alignment: do reasons contain required CE keywords?
KEYWORDS = {"Compliant","Non-compliant","Fail","More-information","Auto-fail"}
def has_alignment(reason):
    return any(k.lower() in reason.lower() for k in KEYWORDS)

df_sem["aligned_reason"] = df_sem["reason"].apply(has_alignment)
align_stats = df_sem["aligned_reason"].mean()*100
print(f"\nMarking alignment: {align_stats:.1f}% of reasons contain compliance keywords")

# 5c. Consistency: unique reasons per (question_id, label)
reason_var = (
    df_sem.groupby(["question_id","predicted_compliance"])["reason"]
          .nunique()
          .reset_index(name="unique_reasons")
          .sort_values("unique_reasons", ascending=False)
)
print("\nTop variability in reasons (more unique = less consistent):")
print(reason_var.head(15).to_string(index=False))


# ---------------------------------------------------------------------
# === 6) Sample for manual inspection ===
# ---------------------------------------------------------------------
print("\nSample semantic-frame predictions with reasons:")
cols = [c for c in ["file","question_id","answer_text","predicted_compliance","reason"] if c in df_sem.columns]
try:
    display(df_sem[cols].head(10))
except NameError:
    print(df_sem[cols].head(10).to_string(index=False))



Reason coverage: 918/918 (100.00%)

Coverage by predicted label:
                      total  with_reason  pct_with_reason
predicted_compliance                                     
Compliant               668          668            100.0
Fail                     93           93            100.0
More-information        148          148            100.0
Non-compliant             8            8            100.0
Unknown                   1            1            100.0

Specificity (% reasons with extracted evidence):
predicted_compliance
Compliant           39.1
Fail                 4.3
More-information     2.7
Non-compliant        0.0
Unknown              0.0

Marking alignment: 74.4% of reasons contain compliance keywords

Top variability in reasons (more unique = less consistent):
question_id predicted_compliance  unique_reasons
       A2.7            Compliant              60
       A2.4            Compliant              50
      A2.10            Compliant              48
       A2.

file question_id  \
11  answers (1).pdf       A2.10   
12  answers (1).pdf        A2.3   
13  answers (1).pdf        A2.4   
14  answers (1).pdf      A2.4.1   
15  answers (1).pdf        A2.5   
16  answers (1).pdf        A2.6   
17  answers (1).pdf        A2.7   
18  answers (1).pdf      A2.7.1   
19  answers (1).pdf        A2.8   
20  answers (1).pdf        A2.9   

                                          answer_text predicted_compliance  \
11  David MacDonald\nNotes:\nResponsible Person Ro...            Compliant   
12  A small site comprising of buildings 17, 19, 2...            Compliant   
13                                                                    Fail   
14            There are no thin client devices in use            Compliant   
15                                                                    Fail   
16                                                                    Fail   
17           Main School network at 17-23 Queens Road            Compliant   
18  No home workers are in scope, all staff are ba...            Compliant   
19                                                                    Fail   
20                    Microsoft 365, Google Workspace            Compliant   

                                               reason  
11  Compliant: Name ('David MacDonald') and role (...  
12  Compliant: Specific location(s) identified wit...  
13                                   Answer is blank.  
14  Compliant: Explicit phrase indicates no thin c...  
15                                   Answer is blank.  
16                                   Answer is blank.  
17  Compliant: 23 network(s) listed; location(s): ...  
18  Compliant: Applicant clearly states no home or...  
19                                   Answer is blank.  
20  Compliant: Cloud services listed – microsoft 3...

**Reason coverage**


All 918 predictions returned both a label and a reason, giving 100% coverage. Every compliance category, including Compliant, Fail, More-information, and Non-compliant, produced reasons, confirming rule consistency.

**Specificity**


Evidence-based reasons appeared most in Compliant cases (39.1%), where answers listed items such as devices or services. Fail (4.3%) and More-information (2.7%) were more generic, and Non-compliant gave no extracted evidence. This shows room to enrich negative outcomes with more detail.


**Marking alignment**

About 74% of reasons contained explicit compliance keywords, keeping outputs aligned with the CE marking scheme. The remainder relied on descriptive text, which may be less clear to assessors.

**Variability**

Some questions, especially scope and inventory (e.g., A2.7, A2.4), produced many unique reasons, while others (e.g., A6.2.x) were more consistent. High variability shows flexibility but suggests templating could improve uniformity.

**Sample inspection**

Examples confirm accuracy: named roles (A2.10), negative declarations (A2.4.1), and listed services (A2.9) were extracted correctly, while blanks (A2.4, A2.5) were flagged as Fail. This shows the rules balance evidence extraction with conservative handling of vague or empty answers.